import { describe, expect, it } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import { WatchlistEngineTab } from "@/app/tabs/garbage/WatchlistEngineTab";
import type { CentralBankSnapshot } from "@/app/types";

const snapshots: CentralBankSnapshot[] = [
  {
    currency: "USD",
    countryCode: "US",
    bankName: "Federal Reserve",
    flag: "US",
    currentPolicyRate: "5.00",
    previousPolicyRate: "4.75",
    currentInflationRate: "2.00",
    previousInflationRate: "2.20",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "EUR",
    countryCode: "EU",
    bankName: "European Central Bank",
    flag: "EU",
    currentPolicyRate: "2.00",
    previousPolicyRate: "2.00",
    currentInflationRate: "2.60",
    previousInflationRate: "2.80",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "GBP",
    countryCode: "GB",
    bankName: "Bank of England",
    flag: "GB",
    currentPolicyRate: "4.25",
    previousPolicyRate: "4.25",
    currentInflationRate: "2.20",
    previousInflationRate: "2.40",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "JPY",
    countryCode: "JP",
    bankName: "Bank of Japan",
    flag: "JP",
    currentPolicyRate: "0.10",
    previousPolicyRate: "0.00",
    currentInflationRate: "2.80",
    previousInflationRate: "2.60",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "AUD",
    countryCode: "AU",
    bankName: "Reserve Bank of Australia",
    flag: "AU",
    currentPolicyRate: "4.10",
    previousPolicyRate: "4.10",
    currentInflationRate: "3.10",
    previousInflationRate: "3.30",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "CAD",
    countryCode: "CA",
    bankName: "Bank of Canada",
    flag: "CA",
    currentPolicyRate: "3.25",
    previousPolicyRate: "3.25",
    currentInflationRate: "2.40",
    previousInflationRate: "2.50",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "NZD",
    countryCode: "NZ",
    bankName: "Reserve Bank of New Zealand",
    flag: "NZ",
    currentPolicyRate: "3.80",
    previousPolicyRate: "3.80",
    currentInflationRate: "3.40",
    previousInflationRate: "3.50",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "CHF",
    countryCode: "CH",
    bankName: "Swiss National Bank",
    flag: "CH",
    currentPolicyRate: "1.00",
    previousPolicyRate: "1.00",
    currentInflationRate: "1.20",
    previousInflationRate: "1.30",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
];

describe("WatchlistEngineTab", () => {
  it("renders the watchlist engine shell and ranked table", () => {
    const html = renderToStaticMarkup(
      <WatchlistEngineTab snapshots={snapshots} onBack={() => {}} />,
    );

    expect(html).toContain("Watchlist Engine");
    expect(html).toContain("Macro-ranked FX watchlist.");
    expect(html).toContain("Ranked Pairs");
    expect(html).toContain("Pairs ranked by macro gap.");
    expect(html).toContain("Showing");
    expect(html).toContain("#1 - #5");
    expect(html).toContain("Top Driver");
    expect(html).toContain("EURUSD");
    expect(html).toContain("Bullish quote");
    expect(html).not.toContain("Methodology / Limits");
    expect(html).not.toContain("More Details");
    expect(html).not.toContain("Coverage");
    expect(html).not.toContain("View");
    expect(html).not.toContain("Details");
    expect(html).not.toContain("Rank #6");
  });
});
