export function IsmScoringNotes() { return <>
    <p>Positive USD score → EURUSD Short · Negative → EURUSD Long. The final bias resolves the latest available monthly context once. V2 also shows the earlier publication snapshots for comparison; their scores are not added together. The table shows each sector's inputs at its own release. Missing components receive no redistributed weight.</p>
    <p>Services leads with 70%; Manufacturing has 30%. Services keeps its v1 weights. Manufacturing uses orders 50%, employment 35%, prices paid 15%. Components compare their latest index with max(50, preceding three-month average), using supplied Revised Previous for the nearest month. Below-50 rebounds remain declines. Weights and the floor are prototype interpretation choices.</p>
    <p>Demand, labor and prices are three evidence groups across both sectors. Related orders/activity readings do not count as separate confirmations. Sector disagreement or opposing demand/employment votes cap evidence at moderate; narrow leads, missing components and ties give weak evidence. Headline composites do not vote. Manufacturing production, inventories and supplier deliveries are unavailable and are not inferred.</p>
    <p>One chart symbol groups the reference month's two publications at the first publication. Both sectors retain their real timestamps and use only observations available at each release. No older sector month is carried into the current group. Before a report arrives its section stays pending. January 2015 history and the 24-earlier-observation gate still apply.</p>
    <p>Scatter Plot → Scoring signal exposes each source component. V2 and v3 share the saved sector boundaries; existing Services settings are retained from v1. Previews stay on the chart until applied. Known timing discrepancies exclude a sector; no broker dates are silently corrected. Official date checks cover 2026 plus a weekend check, not every historical timestamp. Historical comparisons retain provider values and may contain revisions or timing errors; this is a reconstruction from stored data.</p>
    <p>No forecasts, market prices, NFP, CPI or Fed decisions enter this ISM context. Evidence and change size do not predict a price move.</p>
  </>
}
