import { ScoringSection, ScoringNotes } from '../../../../../../shared/ui/ScoringSection'
export function IsmScoringNotes() { return <>
    <ScoringSection title="How this scorer works" collapsible><ScoringNotes items={[
        { label: 'Result & snapshots', content: <>Positive USD score → EURUSD Short · Negative → EURUSD Long. The final bias resolves the latest available monthly context once. Earlier publications supply their own sector readings; their publication-time totals are not added together. The table shows each sector's inputs at its own release. Missing components receive no redistributed weight.</> },
        { label: 'Sector weights & benchmarks', content: <>Services leads with 70%; Manufacturing has 30%. Services uses orders 35%, business activity 25%, employment 25%, prices paid 15%. Manufacturing uses orders 50%, employment 35%, prices paid 15%. Components compare their latest index with max(50, preceding three-month average), using supplied Revised Previous for the nearest month. Below-50 rebounds remain declines. Weights and the floor are prototype interpretation choices.</> },
        { label: 'Evidence groups', content: <>Demand, labor and prices are three evidence groups across both sectors. Related orders/activity readings do not count as separate confirmations. Sector disagreement or opposing demand/employment votes cap evidence at moderate; narrow leads, missing components and ties give weak evidence. Headline composites do not vote. Manufacturing production, inventories and supplier deliveries are unavailable and are not inferred.</> },
        { label: 'Publication timing', content: <>One chart symbol groups the reference month's two publications at the first publication. Both sectors retain their real timestamps and use only observations available at each release. No older sector month is carried into the current group. Before a report arrives its section stays pending. January 2015 history and the 24-earlier-observation gate still apply.</> },
        { label: 'Calibration & data coverage', content: <>Scatter Plot → Scoring signal exposes each source component. The current scorer uses the saved sector boundaries; existing Services settings are retained. Previews stay on the chart until applied. Known timing discrepancies exclude a sector; no broker dates are silently corrected. Official date checks cover 2026 plus a weekend check, not every historical timestamp. Historical comparisons retain provider values and may contain revisions or timing errors; this is a reconstruction from stored data.</> },
        { label: 'Scope', content: <>No forecasts, market prices, NFP, CPI or Fed decisions enter this ISM context. Evidence and change size do not predict a price move.</> }
      ]} /></ScoringSection>
    </>
}
