import { describe, expect, it } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import { MacroStatePrototypeTab } from "@/app/tabs/MacroStatePrototypeTab";
import type { CentralBankSnapshot } from "@/app/types";

const snapshots: CentralBankSnapshot[] = [
  {
    currency: "USD",
    countryCode: "US",
    bankName: "Federal Reserve",
    flag: "US",
    currentPolicyRate: "5.00",
    previousPolicyRate: "4.75",
    currentInflationRate: "2.00",
    previousInflationRate: "2.20",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "EUR",
    countryCode: "EU",
    bankName: "European Central Bank",
    flag: "EU",
    currentPolicyRate: "2.00",
    previousPolicyRate: "2.00",
    currentInflationRate: "2.60",
    previousInflationRate: "2.80",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "GBP",
    countryCode: "GB",
    bankName: "Bank of England",
    flag: "GB",
    currentPolicyRate: "4.25",
    previousPolicyRate: "4.25",
    currentInflationRate: "2.20",
    previousInflationRate: "2.40",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "JPY",
    countryCode: "JP",
    bankName: "Bank of Japan",
    flag: "JP",
    currentPolicyRate: "0.10",
    previousPolicyRate: "0.00",
    currentInflationRate: "2.80",
    previousInflationRate: "2.60",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "AUD",
    countryCode: "AU",
    bankName: "Reserve Bank of Australia",
    flag: "AU",
    currentPolicyRate: "4.10",
    previousPolicyRate: "4.10",
    currentInflationRate: "3.10",
    previousInflationRate: "3.30",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "CAD",
    countryCode: "CA",
    bankName: "Bank of Canada",
    flag: "CA",
    currentPolicyRate: "3.25",
    previousPolicyRate: "3.25",
    currentInflationRate: "2.40",
    previousInflationRate: "2.50",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "NZD",
    countryCode: "NZ",
    bankName: "Reserve Bank of New Zealand",
    flag: "NZ",
    currentPolicyRate: "3.80",
    previousPolicyRate: "3.80",
    currentInflationRate: "3.40",
    previousInflationRate: "3.50",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
  {
    currency: "CHF",
    countryCode: "CH",
    bankName: "Swiss National Bank",
    flag: "CH",
    currentPolicyRate: "1.00",
    previousPolicyRate: "1.00",
    currentInflationRate: "1.20",
    previousInflationRate: "1.30",
    policyRateSource: "released_actual",
    policyRateSourceTitle: null,
    policyRateSourceTime: null,
    inflationSource: "released_actual",
    inflationSourceTitle: null,
    inflationSourceTime: null,
    lastRateReleaseAt: null,
    lastCpiReleaseAt: null,
    nextRateEventAt: null,
    nextRateEventTitle: null,
    nextCpiEventAt: null,
    nextCpiEventTitle: null,
    status: "ok",
    notes: [],
  },
];

describe("MacroStatePrototypeTab", () => {
  it("renders the standalone macro state shell with selector, verdict area, and limits", () => {
    const html = renderToStaticMarkup(
      <MacroStatePrototypeTab snapshots={snapshots} onBack={() => {}} />,
    );

    expect(html).toContain("Macro State");
    expect(html).toContain("Select Pair");
    expect(html).toContain("Macro Bias");
    expect(html).toContain("Selected Pair");
    expect(html).toContain("Composite Score Methodology");
    expect(html).toContain("How the numbers are produced");
    expect(html).toContain("Composite score = 35% real-rate proxy + 30% policy rate level + 20% policy direction + 15% inflation direction");
    expect(html).toContain("Current Pair Output");
    expect(html).toContain("Verdict Rule");
    expect(html).toContain("Current Active Regime");
    expect(html).toContain("Base vs Quote");
    expect(html).toContain("AUDJPY");
    expect(html).toContain("Pair Selector");
    expect(html).toContain("If the macro gap is below");
    expect(html).not.toContain("Event Replay");
    expect(html).not.toContain("What This Means For Manual TA");
    expect(html).not.toContain("Cautions / Limits");
  });
});
