import assert from 'node:assert/strict'
import React from 'react'
import {createServer} from 'vite'
import {Window} from 'happy-dom'
const server=await createServer({server:{middlewareMode:true,hmr:false}}),dom=new Window({url:'http://localhost:5173'})
const globals={window:dom,document:dom.document,HTMLElement:dom.HTMLElement,Node:dom.Node,navigator:dom.navigator,localStorage:dom.localStorage,IS_REACT_ACT_ENVIRONMENT:true}
const previous=new Map([...Object.keys(globals),'Worker','fetch'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]))
for(const[k,v]of Object.entries(globals))Object.defineProperty(globalThis,k,{configurable:true,writable:true,value:v})
const {createRoot}=await import('react-dom/client'),roots=[]
const timers=new Map();let timerId=0
dom.setTimeout=(fn,ms)=>{timers.set(++timerId,{fn,ms});return timerId};dom.clearTimeout=id=>timers.delete(id)
const mount=Component=>{const div=document.createElement('div');document.body.append(div);const root=createRoot(div);roots.push(root);return{div,render:props=>React.act(async()=>{root.render(React.createElement(Component,props));await new Promise(resolve=>setImmediate(resolve))})}}
let posts=0,created=0,terminated=0,revision=1
try{
  const {calculateR1}=await server.ssrLoadModule('./src/scoring-system/r1/analysis.ts')
  const {calculateR1Pair}=await server.ssrLoadModule('./src/scoring-system/r1/pair.ts')
  const {calculateR1History}=await server.ssrLoadModule('./src/scoring-system/r1/history.ts')
  globalThis.Worker=class{constructor(){created++}postMessage({id,input}){posts++;Promise.resolve().then(()=>{if(!this.closed)this.onmessage?.({data:{id,result:input.release?calculateR1Pair(input):calculateR1History(input)}})})}terminate(){this.closed=true;terminated++}}
  const {R1Score}=await server.ssrLoadModule('./src/inspector/scoring/R1Score.tsx')
  const {InspectorPanel}=await server.ssrLoadModule('./src/inspector/InspectorPanel.tsx')
  const {groupInspectorReleases,defaultInspectorPreferences,inspectorStorageKey}=await server.ssrLoadModule('./src/inspector/inspector-data.ts')
  const {r1Profiles}=await server.ssrLoadModule('./src/scoring-system/r1/profiles.ts')
  const {saveR1Settings,readR1Settings,r1SettingsKey}=await server.ssrLoadModule('./src/scoring-system/r1/settings.ts')
  const {exportWorkspace,restoreWorkspace}=await server.ssrLoadModule('./src/workspace-portability/workspace-snapshot.ts')
  const {r1ScatterModel}=await server.ssrLoadModule('./src/scatter-plot/inspection/r1-scatter-model.ts')
  const {ScatterPlotDock}=await server.ssrLoadModule('./src/scatter-plot/dock/ScatterPlotDock.tsx')
  const {R1ScoringSettings}=await server.ssrLoadModule('./src/fundamental-tools/settings/R1ScoringSettings.tsx')
  const {magnitudeFamilies}=await server.ssrLoadModule('./src/inspector/magnitude/magnitude-families.ts')
  const {r1DefaultFreshness}=await server.ssrLoadModule('./src/scoring-system/r1/freshness.ts')
  const {DisplayClockContext}=await server.ssrLoadModule('./src/appearance/time-display/useDisplayClock.ts')
  const {defaultChartClock}=await server.ssrLoadModule('./src/appearance/time-display/chart-clock.ts')
  const at=Date.UTC(2026,2,11,12,30)
  let rows=r1Profiles['us-cpi'].components.map((c,i)=>({value_id:String(i),event_id:c.seriesId,release_at:at,chart_time_seconds:at/1000,server_time_seconds:at/1000,period_seconds:Date.UTC(2026,1,1)/1000,revision:0,currency:'USD',country_code:'US',country_name:'US',name:'CPI',event_code:'',importance:'high',unit:1,multiplier:0,digits:1,time_mode:0,impact:'none',actual:[.2,2.5,.3,2.4][i],previous:[.3,2.5,.2,2.4][i],forecast:null,revised_previous:null,availability:'observed'}))
  const settings={version:1,selected:['us-cpi'],calibration:{mode:'undefined',limits:Object.fromEntries(r1Profiles['us-cpi'].components.map(c=>[`us-cpi/${c.id}`,[.1,.2,.3]]))}}
  saveR1Settings(settings)
  const release=groupInspectorReleases(rows)[0]
  const originalSchedule={seriesId:'840030006',dueAt:at+30*86400000,knownAt:at-86400000,source:'test-publisher'}
  let planned=[originalSchedule]
  globalThis.fetch=async url=>{const params=new URL('http://localhost'+url).searchParams;return{ok:true,json:async()=>url.endsWith('/health')?{revision,sources:[{id:'test',server_now:1}],collector_error:null}:{source_id:'test',revision,timestamp_convention:'trade_server_time',time_basis:'chart',event_ids:params.get('event_ids')?.split(','),events:rows,coverage:{USD:{missing:[]}},next_cursor:null,r1_source_version:1,r1_schedules:planned}}}
  const app=mount(R1Score);await app.render({release,brokerId:'test',events:[]})
  assert.match(app.div.textContent,/USD Weakening/);assert.match(app.div.textContent,/USD-negative\s*-50/)
  assert.equal(app.div.querySelectorAll('details, summary').length,0,'release and relationship evidence are visible without nested disclosures')
  assert.deepEqual([...app.div.querySelectorAll('[aria-label="Release evidence"] tbody tr')].map(tr=>tr.cells[1].textContent),['50%','20%','15%','15%'])
  const chooseDetails=async(value,owner=app)=>React.act(async()=>{const select=owner.div.querySelector('[aria-label="Scoring details"]');select.value=value;select.dispatchEvent(new dom.Event('change',{bubbles:true}))})
  assert.equal(app.div.querySelector('[aria-label="Relationship freshness"]'),null,'Release inputs is the default; unused detail tables are absent')
  const detailJobs=posts
  await chooseDetails('freshness')
  assert.equal(posts,detailJobs,'Changing detail tables launches no calculation work')
  assert.ok(app.div.querySelector('[aria-label="Publication summary"]'),'Summary remains present above every detail choice')
  const freshnessRow=()=>app.div.querySelector('[aria-label="Relationship freshness"] [data-family="us-cpi"]')
  const freshnessCell=(row,label)=>row.cells[[...row.closest('table').querySelectorAll('thead th')].findIndex(th=>th.textContent===label)]
  assert.ok(freshnessRow(),'freshness sources and dates are rendered by the Details selector')
  assert.match(freshnessRow().textContent,/Scheduled: next release \+ 24 hours/)
  assert.equal(freshnessCell(freshnessRow(),'Expires').querySelector('time').dateTime,new Date(at+31*86400000).toISOString())
  assert.equal(freshnessCell(freshnessRow(),'Age at selected time').textContent,'0 days')
  assert.equal(freshnessCell(freshnessRow(),'Fallback limit').textContent,'45 days','fallback limits remain visible when a known schedule takes priority')
  const posted=posts
  await app.render({release,brokerId:'test',events:[],now:at+1000})
  assert.equal(posts,posted,'display clocks do not recalculate R1 history')
  assert.equal(freshnessCell(freshnessRow(),'Age at selected time').textContent,'0 days','age follows the selected publication clock, not the display clock')
  const poll=async()=>React.act(async()=>{for(const[id,t]of [...timers])if(t.ms===10000){timers.delete(id);t.fn()}await new Promise(resolve=>setImmediate(resolve))})
  revision++;await poll();assert.equal(posts,posted,'identical rows at a new storage revision preserve calculation identity')
  rows=rows.map((r,i)=>i===0?{...r,actual:.4}:r);revision++;await poll()
  assert.ok(posts>posted);assert.match(app.div.textContent,/USD Strengthening/,'genuine corrections propagate despite stale selected-release prop')
  const analysis=calculateR1({release:groupInspectorReleases(rows)[0],events:rows,settings,savedBands:{}})
  const history=calculateR1History({family:'us-cpi',events:rows,at,calibration:settings.calibration,savedBands:{}})
  assert.deepEqual(history[0],analysis.assessment,'history worker and Inspector share the exact assessment')
  const model=r1ScatterModel(history,'core-monthly',release.id)
  assert.equal(model.inspection.signal.points,analysis.assessment.readings[0].points)
  assert.deepEqual(model.inspection.signal.limits,analysis.assessment.readings[0].limits)
  const previewLimits=[.05,.075,.09],previewModel=r1ScatterModel(history,'core-monthly',release.id,previewLimits)
  assert.equal(previewModel.inspection.signal.points,4)
  assert.equal(history[0].readings[0].points,1,'chart previews never mutate saved history')
  const revisionStage={...history[0],releaseId:'revision-stage',publishedAt:at+1,stage:'revision'}
  const stagePreview=r1ScatterModel([...history,revisionStage],'core-monthly','revision-stage',previewLimits)
  assert.deepEqual(stagePreview.points.map(p=>p.signal.points),[1,4],'GDP-style revision previews do not change momentum bands')
  const tied={...history[0],readings:history[0].readings.map(r=>({...r,calibration:'r1-automatic',limits:[.1,.1,.1]}))}
  assert.doesNotThrow(()=>r1ScatterModel([tied],'core-monthly',release.id),'inherited automatic ties remain displayable')
  assert.equal(r1ScatterModel(history,'core-monthly','missing-release',previewLimits).inspection,null)
  localStorage.setItem(inspectorStorageKey,JSON.stringify({...defaultInspectorPreferences(),detailView:'r1'}))
  const exported=exportWorkspace();await React.act(async()=>{saveR1Settings({...settings,selected:[]});restoreWorkspace(exported)})
  assert.deepEqual(readR1Settings(),settings);assert.ok(exported.entries[r1SettingsKey])
  const panel=mount(InspectorPanel),view={supported:true,selectedRelease:groupInspectorReleases(rows)[0],preferences:{...defaultInspectorPreferences(),detailView:'r1'},allReleases:groupInspectorReleases(rows),releases:groupInspectorReleases(rows),now:at,brokerId:null,brokerTime:false,range:{from:at-1,to:at+1},storage:{coverage:{},loading:false,error:null},rangeDates:{from:'2026-03-01',to:'2026-03-31'},magnitudeHistory:{rows:{}},applyPreferences(){},selectRelease(){}}
  await panel.render({view,symbol:'EURUSD',source:null,error:null,timeDisplay:{mode:'utc',utcOffsetMinutes:0}})
  assert.equal(panel.div.querySelector('[aria-label="Inspector view"]').value,'r1');assert.ok(panel.div.querySelector('[aria-label="USD R1 scoring"]'))
  const settingsButton=panel.div.querySelector('.inspector-header [aria-label="Scoring explanation & settings"]')
  assert.equal(settingsButton.nextElementSibling,panel.div.querySelector('[aria-label="Inspector view"]'),'settings sits immediately before the view selector')
  let navigation
  const onSettings=e=>{navigation=e.detail}
  window.addEventListener('fyodor:fundamental-settings',onSettings)
  const beforeSettings=posts
  await React.act(async()=>settingsButton.click())
  window.removeEventListener('fyodor:fundamental-settings',onSettings)
  assert.deepEqual(navigation,{family:'us-cpi',model:'r1'},'the moved button opens the R1 settings model')
  assert.equal(posts,beforeSettings,'opening settings does not relaunch scoring')
  const jobs=posts
  await panel.render({view:{...view,preferences:{...view.preferences,detailView:'table'}},symbol:'EURUSD',source:null,error:null,timeDisplay:{mode:'utc',utcOffsetMinutes:0}})
  assert.equal(panel.div.querySelector('[aria-label="USD R1 scoring"]'),null);assert.equal(posts,jobs,'hidden R1 does not launch work')
  const dock=mount(ScatterPlotDock)
  await dock.render({brokerId:'test',clockOffsetMs:at+86400000-Date.now(),target:{brokerId:'test',familyId:'us-cpi',releaseId:release.id,at}})
  const dropdown=dock.div.querySelector('[aria-label="Scatter Plot Calculation"]')
  await React.act(async()=>{dropdown.value='r1';dropdown.dispatchEvent(new dom.Event('change',{bubbles:true}));await new Promise(resolve=>setImmediate(resolve))})
  assert.equal(dock.div.querySelector('[aria-label="Scatter Plot Calculation"]').value,'r1')
  assert.match(dock.div.textContent,/R1 evidence: 50/,'mounted Scatter shows the same corrected contribution as Inspector')
  const fundamental=mount(R1ScoringSettings);await fundamental.render({family:'us-cpi'})
  const freshnessJobs=posts
  const editInput=async(field,value)=>React.act(async()=>{
    Object.getOwnPropertyDescriptor(dom.HTMLInputElement.prototype,'value').set.call(field,String(value))
    field.dispatchEvent(new dom.Event('input',{bubbles:true}))
  })
  assert.equal(fundamental.div.querySelector('[aria-label="CPI freshness days"]').value,'45')
  assert.equal(fundamental.div.querySelector('[aria-label="Jobless claims freshness days"]').value,'10')
  assert.equal(fundamental.div.querySelector('[aria-label="Fed action freshness days"]').value,'70')
  await editInput(fundamental.div.querySelector('[aria-label="R1 scheduled release allowance"]'),48)
  assert.equal(posts,freshnessJobs,'editing freshness drafts launches no jobs')
  await React.act(async()=>fundamental.div.querySelector('[aria-label="R1 freshness settings"]').dispatchEvent(new dom.Event('submit',{bubbles:true,cancelable:true})))
  assert.match(freshnessRow().textContent,/Scheduled: next release \+ 48 hours/)
  assert.equal(freshnessCell(freshnessRow(),'Expires').querySelector('time').dateTime,new Date(at+32*86400000).toISOString())
  assert.match(dock.div.textContent,/R1 evidence: 50/,'freshness changes do not change standalone Scatter evidence')
  const portableFreshness=exportWorkspace()
  await React.act(async()=>{saveR1Settings(settings);restoreWorkspace(portableFreshness)})
  assert.equal(readR1Settings().freshness.graceHours,48,'freshness settings survive workspace export/import')
  assert.deepEqual(readR1Settings().calibration,settings.calibration,'freshness settings preserve manual magnitude overrides')
  await editInput(fundamental.div.querySelector('[aria-label="CPI freshness days"]'),0)
  assert.equal([...fundamental.div.querySelectorAll('button')].find(b=>b.textContent==='Apply freshness').disabled,true,'invalid lifetimes cannot be applied')
  await React.act(async()=>[...fundamental.div.querySelectorAll('button')].find(b=>b.textContent==='Reset freshness defaults').click())
  assert.deepEqual(readR1Settings().freshness,r1DefaultFreshness)
  await React.act(async()=>saveR1Settings(settings))
  const editBoundary=async(label,value)=>React.act(async()=>{
    const field=dock.div.querySelector(`[aria-label="${label} R1 upper boundary"]`)
    Object.getOwnPropertyDescriptor(dom.HTMLInputElement.prototype,'value').set.call(field,String(value))
    field.dispatchEvent(new dom.Event('input',{bubbles:true}))
  })
  await chooseDetails('release')
  const beforePreview=posts
  for(const[label,value]of [['Large',.09],['Medium',.075],['Small',.05]])await editBoundary(label,value)
  assert.match(dock.div.textContent,/Preview evidence: 200/)
  assert.equal(dock.div.querySelector('[data-threshold]').getAttribute('data-threshold'),'0.09')
  assert.deepEqual(readR1Settings(),settings,'editing does not save scorer settings')
  assert.match(app.div.textContent,/USD-supportive\s*\+65/,'Inspector remains on saved calibration during preview')
  assert.equal(posts,beforePreview,'boundary previews launch no calculation workers')
  await React.act(async()=>dock.div.querySelector('[aria-label="R1 magnitude boundaries"]').dispatchEvent(new dom.Event('submit',{bubbles:true,cancelable:true})))
  assert.deepEqual(readR1Settings().calibration.limits['us-cpi/core-monthly'],previewLimits)
  assert.equal(fundamental.div.querySelector('[aria-label="us-cpi/core-monthly Small"]').value,'0.05','Scatter Apply updates Fundamental Settings')
  assert.match(dock.div.textContent,/R1 evidence: 200/)
  assert.match(app.div.textContent,/USD-supportive\s*\+215/,'Apply propagates to Inspector')
  const raw=magnitudeFamilies.find(f=>f.familyId==='us-cpi'&&f.currency==='USD').settings
  await React.act(async()=>raw.save(r1Profiles['us-cpi'].components[0].seriesId,[.1,.2,.3]))
  await React.act(async()=>[...dock.div.querySelectorAll('button')].find(b=>b.textContent==='Reset to inherited').click())
  assert.equal(readR1Settings().calibration.limits['us-cpi/core-monthly'],undefined)
  assert.deepEqual(raw.read()[r1Profiles['us-cpi'].components[0].seriesId],[.1,.2,.3],'Reset preserves saved raw boundaries')
  assert.match(dock.div.textContent,/R1 evidence: 50/,'Reset restores compatible saved raw calibration')
  await React.act(async()=>saveR1Settings(settings))
  assert.equal(dock.div.querySelector('[aria-label="Small R1 upper boundary"]').value,'0.1','settings changes elsewhere update the Scatter editor')
  const historyJobs=posts
  await React.act(async()=>[...dock.div.querySelectorAll('button')].find(b=>b.textContent==='Latest release').click())
  assert.equal(posts,historyJobs,'chart selection reuses history rather than recalculating')
  const inputSelect=dock.div.querySelector('[aria-label="R1 Scatter input"]')
  await React.act(async()=>{inputSelect.value='core-annual';inputSelect.dispatchEvent(new dom.Event('change',{bubbles:true}));[...dock.div.querySelectorAll('button')].find(b=>b.textContent==='All history').click()})
  const axis=dock.div.querySelector('[data-scale-axis="x"]')
  await React.act(async()=>axis.dispatchEvent(new dom.KeyboardEvent('keydown',{key:'+',bubbles:true})))
  const rangeBefore=dock.div.querySelector('svg').getAttribute('data-date-from')
  const switchCalculation=async value=>React.act(async()=>{const select=dock.div.querySelector('[aria-label="Scatter Plot Calculation"]');select.value=value;select.dispatchEvent(new dom.Event('change',{bubbles:true}));await new Promise(resolve=>setImmediate(resolve))})
  await switchCalculation('ap');await switchCalculation('r1')
  assert.equal(dock.div.querySelector('[aria-label="R1 Scatter input"]').value,'core-annual','calculation switches retain input selection')
  assert.ok([...dock.div.querySelectorAll('button')].some(b=>b.textContent==='Recent releases'),'calculation switches retain history mode')
  assert.equal(dock.div.querySelector('svg').getAttribute('data-date-from'),rangeBefore,'calculation switches retain axis viewport')
  const latestOriginal={...rows[0],actual:.2,revision:0},laterCorrection={...rows[0],revision:1}
  rows=rows.map((r,i)=>i===0?{...r,r1_vintages:JSON.stringify([{knownAt:at+1000,event:latestOriginal,source:'fixture'},{knownAt:at+3600000,event:laterCorrection,source:'fixture'}])}:r)
  revision++;await poll()
  assert.match(app.div.textContent,/USD Weakening/,'original Inspector snapshot is recovered despite latest corrected table value')
  await chooseDetails('audit')
  assert.match(app.div.textContent,/retrospective/,'audit identifies unverified late capture')
  const withVintages=posts;revision++;await poll()
  assert.equal(posts,withVintages,'identical version metadata at a new revision does not rescore')
  await chooseDetails('freshness')
  planned=[];revision++;await poll()
  assert.equal(freshnessCell(freshnessRow(),'Status').textContent,'Current')
  assert.match(freshnessCell(freshnessRow(),'Applied rule').textContent,/Age-based: 45 days from publication/)
  assert.equal(freshnessCell(freshnessRow(),'Expires').querySelector('time').dateTime,new Date(at+45*86400000).toISOString())
  assert.equal(freshnessCell(freshnessRow(),'Next release').textContent,'Schedule unavailable')
  planned=[{...originalSchedule,knownAt:at+1}];revision++;await poll()
  assert.match(freshnessRow().textContent,/Age-based: 45 days/,'later schedule captures do not rewrite historical eligibility')
  planned=[originalSchedule];revision++;await poll()
  assert.match(freshnessRow().textContent,/Scheduled: next release \+ 24 hours/,'genuine then-known schedules replace age fallback')
  const ClockedScore=({preference,...props})=>React.createElement(DisplayClockContext.Provider,{value:{scope:defaultChartClock,preference}},React.createElement(R1Score,props))
  const clocked=mount(ClockedScore),clockProps={release,brokerId:'test',events:[]}
  await clocked.render({...clockProps,preference:{mode:'utc',utcOffsetMinutes:0}})
  const clockJobs=posts
  await clocked.render({...clockProps,preference:{mode:'fixed-offset',utcOffsetMinutes:420}})
  const localRow=clocked.div.querySelector('[aria-label="Relationship freshness"] [data-family="us-cpi"]')
  const localExpiry=freshnessCell(localRow,'Expires').querySelector('time')
  assert.match(localExpiry.textContent,/19:30/);assert.match(clocked.div.textContent,/UTC\+07:00/)
  assert.equal(localExpiry.dateTime,new Date(at+31*86400000).toISOString())
  assert.equal(posts,clockJobs,'changing displayed expiry timezone never rescales or recalculates evidence')
  const oldRow=(seriesId,published,patch)=>({...rows[0],r1_vintages:undefined,value_id:`age-${seriesId}`,event_id:seriesId,release_at:published,chart_time_seconds:published/1000,server_time_seconds:published/1000,...patch})
  const ageRows=[...rows,oldRow('840140001',at-86400000,{unit:0,multiplier:1,period_seconds:at/1000-8*86400,actual:210,previous:200}),oldRow('840050014',at-43*86400000-18*3600000,{actual:4,previous:4,period_seconds:at/1000-44*86400})]
  await React.act(async()=>saveR1Settings({...settings,selected:['us-cpi','claims','fomc','gdp']}))
  const ages=mount(R1Score);await ages.render({release:groupInspectorReleases(rows)[0],brokerId:null,events:ageRows})
  const ageRow=family=>ages.div.querySelector(`[aria-label="Relationship freshness"] [data-family="${family}"]`)
  assert.equal(freshnessCell(ageRow('claims'),'Age at selected time').textContent,'1 day')
  assert.equal(freshnessCell(ageRow('claims'),'Fallback limit').textContent,'10 days')
  assert.equal(freshnessCell(ageRow('fomc'),'Age at selected time').textContent,'43 days')
  assert.equal(freshnessCell(ageRow('fomc'),'Fallback limit').textContent,'70 days')
  assert.equal(freshnessCell(ageRow('fomc'),'Status').textContent,'Current','an older report can still be eligible without its age being hidden')
  assert.equal(freshnessCell(ageRow('gdp'),'Age at selected time').textContent,'—','unavailable publications do not get an invented zero age')
  assert.equal(freshnessCell(ageRow('gdp'),'Fallback limit').textContent,'45 days','the configured fallback remains visible even without a report')
  const claimRows=[oldRow('840140001',at,{unit:0,multiplier:1,period_seconds:at/1000-7*86400,actual:197,previous:199}),oldRow('840140002',at,{unit:0,multiplier:2,period_seconds:at/1000-14*86400,actual:1.716,previous:1.699})]
  const claimSettings={version:1,selected:['claims'],calibration:{mode:'undefined',limits:{'claims/initial':[10,20,67],'claims/continuing':[26,58,366]}}}
  await React.act(async()=>saveR1Settings(claimSettings))
  const claimRelease=groupInspectorReleases(claimRows)[0]
  localStorage.setItem('fyodor.scoring.r1.details','release')
  const claimApp=mount(R1Score);await claimApp.render({release:claimRelease,brokerId:null,events:claimRows})
  assert.match(claimApp.div.textContent,/USD Weakening/)
  assert.match(claimApp.div.textContent,/Net\s*-5\.62/)
  assert.deepEqual([...claimApp.div.querySelectorAll('[aria-label="Release evidence"] tbody tr')].map(tr=>tr.cells[5].textContent),['Small · 0.2 pts','Small · 0.65 pts'])
  const claimHistory=calculateR1History({family:'claims',events:claimRows,at,calibration:claimSettings.calibration,savedBands:{}})
  assert.deepEqual(claimHistory[0],calculateR1({release:claimRelease,events:claimRows,settings:claimSettings,savedBands:{}}).assessment)
  const claimModel=r1ScatterModel(claimHistory,'continuing',claimRelease.id)
  assert.equal(claimModel.inspection.signal.size,'Small');assert.equal(claimModel.inspection.signal.points,-17/26)
  const claimPreview=r1ScatterModel(claimHistory,'continuing',claimRelease.id,[17,40,100])
  assert.equal(claimPreview.inspection.signal.size,'Small');assert.equal(claimPreview.inspection.signal.points,-1,'fractional preview uses the same endpoint rule')
  assert.equal(claimHistory[0].readings[1].points,-17/26,'preview keeps the saved fractional assessment intact')
  const claimJobs=posts
  await claimApp.render({release:claimRelease,brokerId:null,events:claimRows,now:at+86400000})
  assert.equal(posts,claimJobs,'display clocks do not rescore fractional claims')
  const claimSettingsView=mount(R1ScoringSettings);await claimSettingsView.render({family:'claims'})
  assert.match(claimSettingsView.div.textContent,/Magnitude points interpolate from zero/)
  const claimRaw=magnitudeFamilies.find(f=>f.familyId==='claims'&&f.currency==='USD').settings
  await React.act(async()=>claimRaw.save('840140001',[10,20,67]))
  rows=claimRows;revision++
  const claimDock=mount(ScatterPlotDock);await claimDock.render({brokerId:'test',clockOffsetMs:at+86400000-Date.now(),target:{brokerId:'test',familyId:'claims',releaseId:claimRelease.id,at}})
  await React.act(async()=>{const select=claimDock.div.querySelector('[aria-label="Scatter Plot Calculation"]');select.value='r1';select.dispatchEvent(new dom.Event('change',{bubbles:true}));await new Promise(resolve=>setImmediate(resolve))})
  assert.match(claimDock.div.textContent,/R1 evidence: 14/)
  assert.match(claimDock.div.textContent,/Magnitude points: 0\.2/)
  const previewJobs=posts
  await editInput(claimDock.div.querySelector('[aria-label="Small R1 upper boundary"]'),12)
  assert.match(claimDock.div.textContent,/Preview evidence: 11\.67/)
  assert.match(claimApp.div.textContent,/Net\s*-5\.62/,'Claims preview keeps Inspector on saved points')
  assert.equal(posts,previewJobs,'fractional boundary preview launches no workers')
  await React.act(async()=>claimDock.div.querySelector('[aria-label="R1 magnitude boundaries"]').dispatchEvent(new dom.Event('submit',{bubbles:true,cancelable:true})))
  assert.match(claimDock.div.textContent,/R1 evidence: 11\.67/)
  assert.match(claimApp.div.textContent,/Net\s*-7\.95/,'Claims Apply propagates fractional points to Inspector')
  assert.equal(claimSettingsView.div.querySelector('[aria-label="claims/initial Small"]').value,'12')
  await React.act(async()=>[...claimDock.div.querySelectorAll('button')].find(b=>b.textContent==='Reset to inherited').click())
  assert.equal(readR1Settings().calibration.limits['claims/initial'],undefined)
  assert.deepEqual(claimRaw.read()['840140001'],[10,20,67])
  assert.match(claimDock.div.textContent,/R1 evidence: 14/)
  assert.match(claimApp.div.textContent,/Net\s*-5\.62/,'Claims Reset restores fractional points from inherited bands')
  const manufacturingSettings={version:1,selected:['ism-manufacturing'],calibration:{mode:'undefined',limits:{'ism-manufacturing/orders':[2,4,6],'ism-manufacturing/headline':[1,2,3],'ism-manufacturing/employment':[2,4,6],'ism-manufacturing/prices':[4,8,12],'ism-manufacturing/production':[1,2,3],'us-cpi/core-monthly':[.1,.2,.3]}}}
  await React.act(async()=>saveR1Settings(manufacturingSettings))
  planned=[{seriesId:'840040001',dueAt:at+30*86400000,knownAt:at-1,source:'test-publisher'}]
  rows=[['840040006',55.3,53.7],['840040001',54.5,54.5],['840040004',52.7,52.7],['840040002',77.9,77.9]].map(([id,actual,previous])=>oldRow(id,at,{unit:0,multiplier:0,period_seconds:Date.UTC(2026,1,1)/1000,actual,previous}));revision++
  const manufacturingRelease=groupInspectorReleases(rows)[0]
  const manufacturingApp=mount(R1Score);await manufacturingApp.render({release:manufacturingRelease,brokerId:'test',events:rows})
  assert.match(manufacturingApp.div.textContent,/Manufacturing new orders improved and remain expanding/)
  assert.match(manufacturingApp.div.textContent,/USD-ISM-MANUFACTURING-R1\.2/)
  assert.match(manufacturingApp.div.textContent,/Net\s*\+36/)
  const manufacturingTable=manufacturingApp.div.querySelectorAll('[aria-label="Release evidence"] tbody tr')
  assert.equal(manufacturingTable.length,4);assert.deepEqual([...manufacturingTable].map(r=>r.cells[1].textContent),['45%','30%','15%','10%'])
  assert.equal(manufacturingTable[0].cells[5].textContent,'Small · 0.8 pts')
  const manufacturingView=mount(R1ScoringSettings);await manufacturingView.render({family:'ism-manufacturing'})
  assert.match(manufacturingView.div.textContent,/Scores orders, manufacturing conditions, hiring and input-price pressure/)
  for(const id of ['orders','headline','employment','prices'])assert.ok(manufacturingView.div.querySelector(`[aria-label="ism-manufacturing/${id} Small"]`))
  assert.equal(manufacturingView.div.querySelector('[aria-label="ism-manufacturing/production Small"]'),null)
  const manufacturingRaw=magnitudeFamilies.find(f=>f.familyId==='ism-manufacturing'&&f.currency==='USD').settings
  await React.act(async()=>manufacturingRaw.save('840040006',[2,4,6]))
  const {R1ScatterPanel}=await server.ssrLoadModule('./src/scatter-plot/dock/R1ScatterPanel.tsx')
  const {scatterFamilyBindings}=await server.ssrLoadModule('./src/scatter-plot/dock/scatter-family-bindings.ts')
  const manufacturingBinding=scatterFamilyBindings.find(b=>b.family.familyId==='ism-manufacturing')
  const manufacturingDock=mount(R1ScatterPanel),retained=new Map([['r1-component','production']])
  await manufacturingDock.render({brokerId:'test',clockOffsetMs:at+86400000-Date.now(),target:{brokerId:'test',familyId:'ism-manufacturing',releaseId:manufacturingRelease.id,at},binding:manufacturingBinding,viewState:retained,familyOptions:[manufacturingBinding.scope.family],onFamilyChange(){},onMeasureChange(){}})
  assert.equal(manufacturingDock.div.querySelector('[aria-label="R1 Scatter input"]').value,'orders','retired Production selection resolves to Orders')
  assert.equal(manufacturingDock.div.querySelector('[aria-label="R1 Scatter input"]').options.length,4)
  assert.match(manufacturingDock.div.textContent,/R1 evidence: 36/)
  assert.match(manufacturingDock.div.textContent,/Magnitude points: 0\.8/)
  await chooseDetails('freshness',manufacturingApp)
  const manufacturingFreshness=manufacturingApp.div.querySelector('[aria-label="Relationship freshness"] [data-family="ism-manufacturing"]')
  assert.match(manufacturingFreshness.textContent,/Scheduled: next release \+ 24 hours/,'all four readings share one manufacturing publication and freshness slot')
  await chooseDetails('relationships',manufacturingApp)
  assert.deepEqual([...manufacturingApp.div.querySelectorAll('[aria-label="USD evidence as of this publication"] tbody tr')].map(r=>r.cells[1].textContent),['10%','15%','75%'],'routed weights are visible and do not add new budgets')
  await chooseDetails('release',manufacturingApp)
  const manufacturingJobs=posts
  await editInput(manufacturingDock.div.querySelector('[aria-label="Small R1 upper boundary"]'),3)
  assert.match(manufacturingDock.div.textContent,/Preview evidence: 24/)
  assert.equal(posts,manufacturingJobs,'manufacturing preview does not rescore history')
  assert.match(manufacturingApp.div.textContent,/Net\s*\+36/,'preview does not alter Inspector')
  await React.act(async()=>manufacturingDock.div.querySelector('[aria-label="R1 magnitude boundaries"]').dispatchEvent(new dom.Event('submit',{bubbles:true,cancelable:true})))
  assert.match(manufacturingApp.div.textContent,/Net\s*\+24/)
  assert.equal(manufacturingView.div.querySelector('[aria-label="ism-manufacturing/orders Small"]').value,'3')
  assert.deepEqual(readR1Settings().calibration.limits['ism-manufacturing/production'],[1,2,3],'dormant limits remain portable without scoring')
  assert.deepEqual(readR1Settings().calibration.limits['us-cpi/core-monthly'],[.1,.2,.3],'other family settings survive the profile change')
  await React.act(async()=>[...manufacturingDock.div.querySelectorAll('button')].find(b=>b.textContent==='Reset to inherited').click())
  assert.match(manufacturingApp.div.textContent,/Net\s*\+36/)
  assert.match(manufacturingDock.div.textContent,/R1 evidence: 36/)
  assert.equal(readR1Settings().calibration.limits['ism-manufacturing/orders'],undefined)
  assert.deepEqual(manufacturingRaw.read()['840040006'],[2,4,6])
  const manufacturingPortable=exportWorkspace(),savedManufacturing=readR1Settings()
  await React.act(async()=>{saveR1Settings(settings);restoreWorkspace(manufacturingPortable)})
  assert.deepEqual(readR1Settings(),savedManufacturing,'all four input overrides and dormant Production settings round-trip')
  const manufacturingClockJobs=posts
  await manufacturingApp.render({release:manufacturingRelease,brokerId:'test',events:rows,now:at+86400000})
  assert.equal(posts,manufacturingClockJobs,'display clocks do not rescore manufacturing')
  for(const id of ['headline','employment','prices']){
    const beforeSelection=posts
    await React.act(async()=>{const input=manufacturingDock.div.querySelector('[aria-label="R1 Scatter input"]');input.value=id;input.dispatchEvent(new dom.Event('change',{bubbles:true}))})
    assert.equal(posts,beforeSelection,'switching an input uses the existing four-input history')
    assert.match(manufacturingDock.div.textContent,/R1 evidence: 0/)
    assert.equal(manufacturingDock.div.querySelector('[aria-label="Small R1 upper boundary"]').value,id==='headline'?'1':id==='employment'?'2':'4')
  }
  rows=rows.map(r=>r.event_id==='840040002'?{...r,actual:78.9}:r);revision++;await poll()
  assert.match(manufacturingApp.div.textContent,/Net\s*\+38\.5/,'genuine Prices Paid changes reach the assembled Inspector')
  assert.match(manufacturingDock.div.textContent,/R1 evidence: 2\.5/,'Prices Paid uses its own fractional boundaries and 10% weight')
  await React.act(async()=>manufacturingRaw.save('840040002',[4,8,12]))
  const priceJobs=posts
  await editInput(manufacturingDock.div.querySelector('[aria-label="Small R1 upper boundary"]'),2)
  assert.equal(posts,priceJobs,'Prices Paid preview also stays local to Scatter')
  assert.match(manufacturingDock.div.textContent,/Preview evidence: 5/)
  assert.match(manufacturingApp.div.textContent,/Net\s*\+38\.5/)
  await React.act(async()=>manufacturingDock.div.querySelector('[aria-label="R1 magnitude boundaries"]').dispatchEvent(new dom.Event('submit',{bubbles:true,cancelable:true})))
  assert.match(manufacturingApp.div.textContent,/Net\s*\+41/)
  assert.equal(manufacturingView.div.querySelector('[aria-label="ism-manufacturing/prices Small"]').value,'2')
  await React.act(async()=>[...manufacturingDock.div.querySelectorAll('button')].find(b=>b.textContent==='Reset to inherited').click())
  assert.match(manufacturingApp.div.textContent,/Net\s*\+38\.5/)
  assert.equal(readR1Settings().calibration.limits['ism-manufacturing/prices'],undefined)
  console.log('✓ Mounted R1 Inspector, publication corrections, stable polling/clocks, hidden-view cleanup, fractional Claims/manufacturing Scatter parity and workspace portability')
}finally{
  await React.act(async()=>roots.forEach(root=>root.unmount()))
  assert.equal(terminated,created,'all R1 workers terminate on unmount')
  await server.close();dom.happyDOM.abort()
  for(const[k,descriptor]of previous)if(descriptor)Object.defineProperty(globalThis,k,descriptor);else delete globalThis[k]
}
