export type TabId =
  | "overview"
  | "legacy-overview"
  | "currency-candle-strength"
  | "watchlist-engine-prototype"
  | "dashboard"
  | "strength-meter"
  | "event-tools"
  | "terminal-questions"
  | "work-in-progress"
  | "prototyping"
  | "macro-state-prototype"
  | "central-banks"
  | "charts"
  | "calendar";
