import type { CalendarEventExplainer, EventQualityFamily } from "@/app/types";

type CalendarKnowledgeEntry = Omit<CalendarEventExplainer, "family" | "familyLabel"> & {
  familyLabel: string;
};

export const CALENDAR_EVENT_FAMILY_DEFAULTS: Record<EventQualityFamily, CalendarKnowledgeEntry> = {
  policy: {
    familyLabel: "Policy / Rates",
    whatItIs: "This event updates the market on central-bank policy, interest-rate direction, or official guidance.",
    whyTradersCare: "Policy communication can quickly change expectations for currency strength, rate differentials, liquidity, and broad risk appetite.",
    mayAffect: ["The event currency and its major FX pairs", "Rate-sensitive assets", "Gold and broad risk sentiment when the central bank is globally important"],
    priceCaveats: [
      "Markets react to the decision, statement tone, and future guidance together, not just the headline.",
      "If the market already expected the outcome, price can fade quickly instead of extending.",
    ],
    educationalSummary: "Policy events matter because currencies often reprice when traders rethink the path of future rates, liquidity, and central-bank credibility.",
    strongerOutcome: "A more hawkish outcome or tone can support the currency if it implies tighter policy or higher rates than expected.",
    weakerOutcome: "A more dovish outcome or softer tone can weaken the currency if it implies easier policy or lower rates than expected.",
    contextNote: "Policy events are especially powerful when markets are unsure about the next decision or when guidance meaningfully shifts the expected rate path.",
  },
  inflation: {
    familyLabel: "Inflation",
    whatItIs: "This event measures changes in consumer prices or inflation pressure.",
    whyTradersCare: "Inflation helps shape how much pressure a central bank may feel to tighten, pause, or ease policy.",
    mayAffect: ["The event currency and its major FX pairs", "Rate expectations", "Gold and yields when the release changes central-bank expectations"],
    priceCaveats: [
      "A hot or soft print does not move price equally in every cycle.",
      "Inflation matters less when traders are focused on growth stress, policy communication, or positioning instead.",
    ],
    educationalSummary: "Inflation releases matter because they change how traders think about future policy, real yields, and whether current rates are restrictive enough.",
    strongerOutcome: "Higher-than-expected inflation can support the currency if traders think it raises the odds of tighter policy or fewer cuts.",
    weakerOutcome: "Lower-than-expected inflation can weaken the currency if traders think it reduces policy-tightening pressure or opens the door to easing.",
    contextNote: "The same inflation surprise can matter very differently depending on whether the central bank is already worried about inflation or already focused on growth weakness.",
  },
  labor: {
    familyLabel: "Labor",
    whatItIs: "This event measures employment conditions, hiring momentum, unemployment, or wage pressure.",
    whyTradersCare: "Labor data helps traders judge economic resilience, consumer strength, and whether wage pressure may spill into inflation.",
    mayAffect: ["The event currency and its major FX pairs", "Short-term rate expectations", "Broad risk mood when the labor market is seen as a growth anchor"],
    priceCaveats: [
      "Headlines can mislead if wages, participation, or revisions point the other way.",
      "Labor events can create fast first moves that are later rebalanced once the details are digested.",
    ],
    educationalSummary: "Labor data matters because jobs and wages influence growth, inflation pressure, and how confidently a central bank can stay tight or pivot.",
    strongerOutcome: "Stronger hiring or wages can support the currency if traders read it as economic strength or inflation persistence.",
    weakerOutcome: "Weaker employment data can hurt the currency if traders read it as growth deterioration or a reason for looser policy later.",
    contextNote: "Labor data becomes especially important when the market is debating recession risk, wage inflation, or whether the economy is finally slowing.",
  },
  gdp: {
    familyLabel: "GDP",
    whatItIs: "This event measures the economy's broad growth rate over the reported period.",
    whyTradersCare: "GDP helps traders judge whether the economy is accelerating, slowing, or diverging from other major economies.",
    mayAffect: ["The event currency and its major FX pairs", "Growth-sensitive assets", "Broader sentiment if the economy is systemically important"],
    priceCaveats: [
      "GDP is important, but it is often less explosive than policy or inflation events because it can lag current conditions.",
      "Revisions, composition, and what markets already expected all matter.",
    ],
    educationalSummary: "GDP matters because currencies often strengthen when traders believe an economy is outperforming peers or can handle tighter policy.",
    strongerOutcome: "A stronger-than-expected GDP print can support the currency if it reinforces a growth advantage or reduces easing expectations.",
    weakerOutcome: "A weaker-than-expected GDP print can weaken the currency if it raises slowdown concerns or increases easing expectations.",
    contextNote: "GDP usually matters more when markets are questioning whether a country is slipping into slowdown or outperforming peers in a visible way.",
  },
  activity: {
    familyLabel: "PMI / ISM / Activity",
    whatItIs: "This event tracks business activity, new orders, sentiment, or consumer spending momentum.",
    whyTradersCare: "Activity data gives traders a faster pulse on growth conditions than slower-moving macro releases.",
    mayAffect: ["The event currency and its major FX pairs", "Equity index sentiment", "Commodities or cyclical assets when growth implications are strong"],
    priceCaveats: [
      "These releases can matter a lot when they are one of the first signs of a turn, but less when the macro story is already well known.",
      "Subcomponents such as prices, employment, or new orders can matter more than the headline.",
    ],
    educationalSummary: "Activity indicators matter because they can shift growth expectations earlier than slower official reports, especially around turning points.",
    strongerOutcome: "A stronger activity reading can support the currency if it implies healthier growth or better business momentum.",
    weakerOutcome: "A weaker activity reading can weigh on the currency if it suggests growth is cooling or demand is deteriorating.",
    contextNote: "Activity data is most useful when the market is searching for early signs that the economy is improving, stalling, or breaking trend.",
  },
  trade_confidence: {
    familyLabel: "Trade / Confidence",
    whatItIs: "This event tracks trade balance, external demand, or confidence-related measures tied to growth expectations.",
    whyTradersCare: "These releases can shape growth expectations and show whether demand, sentiment, or external balance is improving or worsening.",
    mayAffect: ["The event currency and its major FX pairs", "Growth-sensitive sectors or regional risk sentiment", "Theme validation for broader macro positioning"],
    priceCaveats: [
      "These events usually matter less than policy, inflation, or labor unless they strongly reinforce a developing macro theme.",
      "The market may ignore them when larger scheduled releases are nearby.",
    ],
    educationalSummary: "Trade and confidence releases matter most when they help confirm whether demand, competitiveness, or sentiment is improving or rolling over.",
    strongerOutcome: "A stronger result can support the currency if it improves the growth or external-balance picture.",
    weakerOutcome: "A weaker result can pressure the currency if it adds to concerns about demand, competitiveness, or sentiment.",
    contextNote: "These events often work best as context-builders rather than standalone market movers unless the surprise is unusually large.",
  },
};

export const CALENDAR_EVENT_TITLE_OVERRIDES: Record<string, CalendarKnowledgeEntry> = {
  "nonfarm payrolls": {
    familyLabel: "Labor",
    whatItIs: "Nonfarm Payrolls tracks how many jobs were added or lost across the U.S. economy outside farm work.",
    whyTradersCare: "It is one of the most market-sensitive U.S. labor releases because it shapes views on growth, wages, and Fed pressure.",
    mayAffect: ["USD pairs", "Gold", "U.S. equity indices and Treasury expectations", "Broader global risk sentiment"],
    priceCaveats: [
      "The market often cares about wages, revisions, and unemployment alongside the headline payroll number.",
      "A strong headline can still fade if other labor details are softer than expected.",
    ],
    educationalSummary: "NFP matters because it is treated as a fast pulse check on U.S. labor strength and whether the economy is running hot enough to influence Fed expectations.",
    strongerOutcome: "A stronger-than-expected report can support USD if it reinforces economic resilience or keeps Fed expectations firmer.",
    weakerOutcome: "A weaker-than-expected report can hurt USD if it raises slowdown concerns or softens the expected policy path.",
    contextNote: "NFP is most powerful when the market is uncertain about U.S. growth, recession risk, or how sticky wage and inflation pressure still are.",
  },
  "unemployment rate": {
    familyLabel: "Labor",
    whatItIs: "This release shows the share of the labor force currently unemployed and actively looking for work.",
    whyTradersCare: "It helps traders judge labor-market slack, recession risk, and how hot or cool the economy may be running.",
    mayAffect: ["The event currency and its major FX pairs", "Rate expectations when the release shifts policy thinking"],
    priceCaveats: [
      "The unemployment rate can be distorted by labor-force participation changes.",
      "It matters more when paired with a broader labor release or when markets are debating slowdown risk.",
    ],
    educationalSummary: "Unemployment matters because central banks and markets use labor slack to judge whether an economy is overheating, stable, or weakening.",
    strongerOutcome: "A lower-than-expected unemployment rate can support the currency if it reinforces labor strength and policy firmness.",
    weakerOutcome: "A higher-than-expected unemployment rate can hurt the currency if it suggests labor cooling or broader growth deterioration.",
    contextNote: "This release usually matters more when the market is looking for confirmation that labor strength is either cracking or staying resilient.",
  },
  "average hourly earnings": {
    familyLabel: "Labor",
    whatItIs: "This release tracks wage growth and gives a direct signal on labor-cost pressure.",
    whyTradersCare: "Wage growth matters because strong wages can feed inflation pressure and influence central-bank policy expectations.",
    mayAffect: ["The event currency and its major FX pairs", "Rate expectations", "Broader inflation-sensitive assets"],
    priceCaveats: [
      "Wages can matter more than headline jobs in some cycles, especially when inflation persistence is the main concern.",
      "A strong wage print can offset a softer payroll headline and vice versa.",
    ],
    educationalSummary: "Wage data matters because it helps traders judge whether labor tightness is still feeding into inflation and future policy pressure.",
    strongerOutcome: "Higher-than-expected wage growth can support the currency if it keeps inflation and policy-tightening concerns alive.",
    weakerOutcome: "Lower-than-expected wage growth can weaken the currency if it reduces policy pressure or signals cooling demand.",
    contextNote: "Wage releases matter most when inflation is sticky and the market is watching whether labor costs are still feeding that story.",
  },
  "cpi": {
    familyLabel: "Inflation",
    whatItIs: "CPI tracks the change in consumer prices paid by households.",
    whyTradersCare: "It is one of the clearest inflation gauges used to reassess central-bank pressure and future rate expectations.",
    mayAffect: ["The event currency and its major FX pairs", "Gold", "Bond-yield expectations", "Risk sentiment when the release shifts policy pricing"],
    priceCaveats: [
      "Headline CPI can be noisy, especially when energy or food swings dominate.",
      "The market often looks deeper into core components, services inflation, and monthly momentum.",
    ],
    educationalSummary: "CPI matters because inflation can directly change how restrictive current policy feels and how far the market thinks the central bank may still need to go.",
    strongerOutcome: "A hotter CPI print can support the currency if traders think it keeps policy tighter or delays expected cuts.",
    weakerOutcome: "A softer CPI print can hurt the currency if traders think it lowers policy pressure or opens the door to easier policy.",
    contextNote: "CPI is most powerful when the market is debating whether inflation is still sticky or finally easing enough to change policy expectations.",
  },
  "core cpi": {
    familyLabel: "Inflation",
    whatItIs: "Core CPI removes some volatile components to show steadier underlying inflation pressure.",
    whyTradersCare: "Core inflation often matters more than headline inflation when traders want to judge persistent price pressure.",
    mayAffect: ["The event currency and its major FX pairs", "Rate expectations", "Gold and yields if policy expectations shift"],
    priceCaveats: [
      "Core CPI can move price more than headline CPI when the market is focused on sticky services inflation.",
      "The release still depends heavily on broader policy and positioning context.",
    ],
    educationalSummary: "Core CPI matters because it helps traders judge whether inflation pressure is broad and persistent rather than being driven by short-lived swings.",
    strongerOutcome: "A stronger core CPI print can support the currency if it reinforces sticky inflation and a firmer policy path.",
    weakerOutcome: "A softer core CPI print can weaken the currency if it suggests underlying inflation is cooling faster than expected.",
    contextNote: "Core CPI often matters most when the market thinks headline inflation is noisy and wants a cleaner read on persistence.",
  },
  "pce": {
    familyLabel: "Inflation",
    whatItIs: "PCE tracks consumer-price changes through a broader spending lens and is closely watched by the Federal Reserve.",
    whyTradersCare: "It can matter even more than CPI in U.S. policy cycles because it aligns more closely with the Fed's preferred inflation framework.",
    mayAffect: ["USD pairs", "Gold", "Fed expectations", "Broader U.S. macro-sensitive assets"],
    priceCaveats: [
      "PCE may move less than CPI when the market already got a strong inflation signal from earlier releases.",
      "Core PCE often carries more weight than headline PCE when inflation persistence is the main focus.",
    ],
    educationalSummary: "PCE matters because it helps traders judge whether inflation is cooling fast enough for the Fed to change tone or policy expectations.",
    strongerOutcome: "A hotter-than-expected PCE print can support USD if it reinforces a tighter expected Fed path.",
    weakerOutcome: "A softer-than-expected PCE print can weaken USD if it supports a softer expected Fed path.",
    contextNote: "PCE matters most when Fed pricing is highly sensitive and the market is searching for confirmation on the inflation trend.",
  },
  "core pce": {
    familyLabel: "Inflation",
    whatItIs: "Core PCE strips out volatile components to show a steadier read of underlying inflation pressure in the Fed's preferred measure.",
    whyTradersCare: "It is one of the cleanest U.S. inflation inputs for judging whether the Fed can stay patient, cut, or stay tighter for longer.",
    mayAffect: ["USD pairs", "Gold", "Treasury expectations", "Broader macro sentiment around the Fed path"],
    priceCaveats: [
      "Core PCE can matter more than headline inflation when the market is focused on persistent price pressure rather than one-off noise.",
      "The release is often interpreted through the broader policy and growth backdrop, not in isolation.",
    ],
    educationalSummary: "Core PCE matters because it gives traders a cleaner view of whether underlying inflation is easing enough to change Fed expectations.",
    strongerOutcome: "A stronger core PCE print can support USD if it keeps the market leaning toward tighter or slower-easing policy.",
    weakerOutcome: "A softer core PCE print can weigh on USD if it supports a gentler inflation path and softer policy pricing.",
    contextNote: "Core PCE matters most when Fed pricing is sensitive and traders want confirmation that inflation is or is not cooling cleanly.",
  },
  "interest rate decision": {
    familyLabel: "Policy / Rates",
    whatItIs: "This event announces the central bank's current policy-rate decision.",
    whyTradersCare: "It directly affects rate differentials and can quickly reprice the expected path of future policy.",
    mayAffect: ["The event currency and its major FX pairs", "Rate-sensitive assets", "Gold and broader sentiment when the bank is globally important"],
    priceCaveats: [
      "The statement, vote split, and forward guidance often matter as much as the headline rate itself.",
      "A hold can still move price if the tone is surprisingly hawkish or dovish.",
    ],
    educationalSummary: "Rate decisions matter because currencies and yields often reprice when traders adjust what they think the central bank will do next.",
    strongerOutcome: "A more hawkish or tighter-than-expected decision can support the currency if it improves relative yield expectations.",
    weakerOutcome: "A more dovish or softer-than-expected decision can weaken the currency if it reduces relative yield support.",
    contextNote: "This event matters most when the market is unsure about the policy path or when guidance meaningfully shifts forward expectations.",
  },
  "fomc statement": {
    familyLabel: "Policy / Rates",
    whatItIs: "The FOMC statement communicates the Fed's policy decision, reasoning, and broad view of the economy.",
    whyTradersCare: "Markets watch it for subtle changes in tone that can move Fed expectations even when rates stay unchanged.",
    mayAffect: ["USD pairs", "Gold", "U.S. equities", "Treasury yields and global risk sentiment"],
    priceCaveats: [
      "Small wording changes can matter a lot when the market is already leaning hard in one direction.",
      "The statement is often interpreted together with the press conference and projections when available.",
    ],
    educationalSummary: "The FOMC statement matters because it tells traders how the Fed is thinking about inflation, growth, labor, and the next steps in policy.",
    strongerOutcome: "A more hawkish statement can support USD if it suggests tighter policy or fewer cuts than expected.",
    weakerOutcome: "A more dovish statement can weaken USD if it suggests softer policy or more room for easing than expected.",
    contextNote: "The statement matters most when markets are sensitive to even small shifts in the Fed's policy tone or reaction function.",
  },
  "ecb interest rate decision": {
    familyLabel: "Policy / Rates",
    whatItIs: "This event announces the ECB's current policy-rate decision and sets the immediate tone for euro-area policy.",
    whyTradersCare: "It affects euro yield expectations and can quickly change the market's view of the ECB policy path.",
    mayAffect: ["EUR pairs", "European equities and rates", "Broader risk sentiment when ECB tone shifts meaningfully"],
    priceCaveats: [
      "The press conference and guidance often matter as much as the decision itself.",
      "A widely expected hold can still move EUR if tone or risk framing changes.",
    ],
    educationalSummary: "ECB decisions matter because the euro reprices when traders reassess where euro-area policy is heading relative to peers.",
    strongerOutcome: "A more hawkish ECB outcome can support EUR if it improves relative yield expectations.",
    weakerOutcome: "A more dovish ECB outcome can pressure EUR if it softens relative policy support.",
    contextNote: "ECB events matter most when the market is uncertain about the euro-area growth/inflation mix or the next policy turn.",
  },
  "boe interest rate decision": {
    familyLabel: "Policy / Rates",
    whatItIs: "This event announces the Bank of England's current policy-rate decision and helps frame the UK policy path.",
    whyTradersCare: "It changes how traders think about GBP yield support, UK inflation risks, and the balance between growth and policy restraint.",
    mayAffect: ["GBP pairs", "UK rates and equities", "Broader risk mood if the policy signal is surprising"],
    priceCaveats: [
      "Vote splits and guidance can matter more than the headline rate itself.",
      "The reaction depends on how the BoE balances inflation risks against growth weakness.",
    ],
    educationalSummary: "BoE decisions matter because GBP often reprices when traders rethink how restrictive UK policy may stay relative to peers.",
    strongerOutcome: "A more hawkish BoE outcome can support GBP if it keeps relative rate support firmer.",
    weakerOutcome: "A more dovish BoE outcome can weigh on GBP if it suggests softer policy ahead.",
    contextNote: "BoE events matter most when inflation remains sticky or the market is debating whether UK growth is weakening too much for current policy.",
  },
  "gdp q/q": {
    familyLabel: "GDP",
    whatItIs: "GDP q/q measures quarter-on-quarter growth momentum in the economy.",
    whyTradersCare: "It helps traders judge whether the economy is accelerating, stagnating, or slowing relative to expectations.",
    mayAffect: ["The event currency and its major FX pairs", "Growth-sensitive assets", "Broader macro theme confidence"],
    priceCaveats: [
      "GDP can be less explosive than policy or inflation releases, especially when the report lags current conditions.",
      "Revisions and report details can matter as much as the headline number.",
    ],
    educationalSummary: "GDP q/q matters because it gives a broad read on whether growth is outperforming or underperforming what the market expected.",
    strongerOutcome: "A stronger GDP q/q result can support the currency if it strengthens the growth outlook or reduces easing expectations.",
    weakerOutcome: "A weaker GDP q/q result can hurt the currency if it raises slowdown concerns or supports easier policy expectations.",
    contextNote: "GDP matters most when the market is actively debating recession risk, relative growth divergence, or how durable recent momentum really is.",
  },
  "retail sales": {
    familyLabel: "PMI / ISM / Activity",
    whatItIs: "Retail Sales tracks consumer spending activity and helps show how demand is holding up.",
    whyTradersCare: "Consumer spending is a key engine of growth, so this release can shift expectations for economic resilience.",
    mayAffect: ["The event currency and its major FX pairs", "Growth-sensitive assets", "Risk sentiment when demand strength is a major theme"],
    priceCaveats: [
      "Headline strength can be distorted by volatile categories or inflation effects.",
      "Control-group or core details often matter more than the broad headline move.",
    ],
    educationalSummary: "Retail Sales matters because spending strength or weakness helps traders judge whether the consumer is still supporting broader growth.",
    strongerOutcome: "A stronger Retail Sales print can support the currency if it reinforces a resilient growth story.",
    weakerOutcome: "A weaker Retail Sales print can weigh on the currency if it signals cooling demand and slower growth.",
    contextNote: "Retail Sales matters most when the market is trying to judge whether consumers are still holding up or finally rolling over.",
  },
  "ism manufacturing pmi": {
    familyLabel: "PMI / ISM / Activity",
    whatItIs: "ISM Manufacturing PMI tracks manufacturing activity, new orders, prices, and employment conditions.",
    whyTradersCare: "It gives traders an early read on industrial momentum and whether the economy is improving or slowing.",
    mayAffect: ["The event currency and its major FX pairs", "Equity index sentiment", "Commodity and cyclical themes when growth implications are strong"],
    priceCaveats: [
      "Subcomponents such as new orders or prices can matter more than the headline PMI number.",
      "Manufacturing PMI can matter less when services or policy are dominating the macro story.",
    ],
    educationalSummary: "Manufacturing PMI matters because it provides a quick pulse on business momentum before slower official data arrives.",
    strongerOutcome: "A stronger PMI print can support the currency if it implies improving business activity and growth momentum.",
    weakerOutcome: "A weaker PMI print can hurt the currency if it signals slowing activity or deteriorating demand.",
    contextNote: "This release matters most when traders are looking for early evidence that the economy is re-accelerating or rolling over.",
  },
  "ism services pmi": {
    familyLabel: "PMI / ISM / Activity",
    whatItIs: "ISM Services PMI tracks activity, orders, employment, and pricing across the service sector.",
    whyTradersCare: "Services often dominate modern economies, so this release can strongly shape growth and inflation expectations.",
    mayAffect: ["The event currency and its major FX pairs", "Equity index sentiment", "Rates and risk mood when the growth signal is strong"],
    priceCaveats: [
      "The market often watches prices-paid and employment components closely, not just the headline.",
      "A strong services read can matter more than manufacturing when the service sector is the main growth engine.",
    ],
    educationalSummary: "Services PMI matters because it helps traders judge whether the larger service economy is expanding cleanly or losing momentum.",
    strongerOutcome: "A stronger services PMI print can support the currency if it reinforces growth resilience or inflation persistence.",
    weakerOutcome: "A weaker services PMI print can pressure the currency if it suggests demand is cooling or the economy is losing traction.",
    contextNote: "This release matters most when traders want a timely read on the broader economy rather than just one narrower sector.",
  },
  pmi: {
    familyLabel: "PMI / ISM / Activity",
    whatItIs: "PMI releases measure business conditions such as output, new orders, employment, and prices.",
    whyTradersCare: "They provide a fast read on whether business activity is expanding, slowing, or contracting.",
    mayAffect: ["The event currency and its major FX pairs", "Equity and cyclical sentiment", "Growth-sensitive themes"],
    priceCaveats: [
      "The headline PMI is useful, but traders often care just as much about prices, orders, and employment details.",
      "PMI releases matter more when the market is searching for early turning-point evidence.",
    ],
    educationalSummary: "PMI data matters because it gives traders earlier clues about growth momentum than slower official reports.",
    strongerOutcome: "A stronger PMI result can support the currency if it implies healthier growth or improving business momentum.",
    weakerOutcome: "A weaker PMI result can hurt the currency if it signals deteriorating demand or weaker activity.",
    contextNote: "PMI releases are most useful when the market is uncertain about whether activity is stabilizing, re-accelerating, or breaking lower.",
  },
};

export const CALENDAR_EVENT_GENERIC_FALLBACK: CalendarEventExplainer = {
  family: "generic",
  familyLabel: "General Macro Event",
  whatItIs: "This event updates the market on an economic or policy-related data point.",
  whyTradersCare: "Traders care because new macro information can change expectations for growth, inflation, policy, and relative currency strength.",
  mayAffect: ["The event currency and its major FX pairs", "Theme-related assets if the release changes the broader macro picture"],
  priceCaveats: [
    "Not every release moves price meaningfully, especially if the result was already expected.",
    "The surrounding macro theme often matters more than the event in isolation.",
  ],
  educationalSummary: "Macro events matter when they change the market's expectations, not just because they appear on the calendar.",
  strongerOutcome: "A stronger-than-expected result can support the currency if traders see it as growth-positive or policy-supportive.",
  weakerOutcome: "A weaker-than-expected result can hurt the currency if traders see it as growth-negative or policy-softening.",
  contextNote: "Always compare the event to the existing macro story, nearby larger releases, and how much of the outcome the market already priced in.",
};

export const CALENDAR_EVENT_KNOWLEDGE_BACKLOG = [
  "Producer Price Index (PPI)",
  "JOLTS Job Openings",
  "Consumer Confidence",
  "ZEW / Sentix / regional confidence releases",
  "Industrial Production",
  "Housing data families",
  "Current Account",
  "Wholesale inflation / import prices / export prices",
] as const;
