import type { CalendarEventExplainer, EventQualityFamily } from "@/app/types";

export type EventResultDirection = "higher_supports_currency" | "lower_supports_currency" | "contextual";

export interface CalendarEventDefinition extends Omit<CalendarEventExplainer, "family" | "familyLabel"> {
  family: EventQualityFamily | "generic";
  familyLabel: string;
  exactTitles?: string[];
  includeAny?: string[];
  includeAll?: string[][];
  excludeAny?: string[];
  resultDirection: EventResultDirection;
}

function normalizeText(value: string): string {
  return value.trim().toLowerCase();
}

function includesAny(text: string, terms: string[] | undefined): boolean {
  return terms?.some((term) => text.includes(term)) ?? false;
}

function includesAllGroup(text: string, groups: string[][] | undefined): boolean {
  if (!groups || groups.length === 0) return false;
  return groups.some((group) => group.every((term) => text.includes(term)));
}

export const CALENDAR_EVENT_DEFINITIONS: CalendarEventDefinition[] = [
  {
    family: "labor",
    familyLabel: "Labor / Employment",
    exactTitles: ["nonfarm payrolls"],
    includeAny: ["nonfarm payroll"],
    resultDirection: "higher_supports_currency",
    knowledgeDepth: "specific",
    marketSensitivity: "Very high for USD because it can reset growth, wage, inflation, and Fed-path expectations at once.",
    whatItIs: "Nonfarm Payrolls estimates how many U.S. jobs were added or lost outside farm work, government-dependent categories, private households, and nonprofit employees.",
    whyTradersCare: "It is a fast read on U.S. labor momentum. A strong labor market can keep growth resilient and make the Fed less comfortable easing policy quickly.",
    mayAffect: ["USD pairs", "Gold", "U.S. equity indices", "Treasury-yield expectations", "Broad risk sentiment"],
    priceCaveats: [
      "The headline can be overridden by unemployment, wage growth, participation, or revisions.",
      "A strong number can still fade if traders decide it is already priced in or if wage details are soft.",
    ],
    educationalSummary: "NFP is not just a jobs count. In trading workflow it is a stress test of whether the U.S. economy is still strong enough to support USD and rate expectations.",
    strongerOutcome: "A payroll beat usually supports USD when it reinforces growth resilience or reduces near-term Fed-cut expectations.",
    weakerOutcome: "A payroll miss usually pressures USD when it raises slowdown risk or supports easier Fed expectations.",
    contextNote: "For actual trading, compare payrolls, unemployment, wages, and revisions together before trusting the first candle.",
    whatToCompare: ["Actual versus forecast", "Prior-month revision", "Unemployment rate", "Average hourly earnings", "First 5m/15m candle reaction"],
    tradingWorkflow: [
      "Before release: mark USD pairs exposed to the event and avoid treating pre-release drift as confirmation.",
      "At release: read headline, wages, unemployment, and revisions as one package.",
      "After release: trust the direction more if USD moves broadly across EURUSD, GBPUSD, USDJPY, gold, and yields-sensitive symbols.",
    ],
    commonTraps: ["Trading only the payroll headline", "Ignoring revisions", "Assuming the first spike is the final direction"],
  },
  {
    family: "labor",
    familyLabel: "Labor / Employment",
    includeAny: ["unemployment rate"],
    resultDirection: "lower_supports_currency",
    knowledgeDepth: "specific",
    marketSensitivity: "High when markets are debating recession risk, central-bank easing, or labor-market cracks.",
    whatItIs: "The unemployment rate measures the share of the labor force that is unemployed and actively looking for work.",
    whyTradersCare: "It shows labor slack. Rising unemployment can signal weaker growth and can make future policy easing more likely.",
    mayAffect: ["The event currency", "Major pairs containing that currency", "Rate expectations"],
    priceCaveats: [
      "Participation changes can move the unemployment rate without a clean change in labor demand.",
      "It should be read with employment change, wage growth, and revisions.",
    ],
    educationalSummary: "In workflow terms, unemployment tells you whether the labor market is tightening, stable, or starting to crack.",
    strongerOutcome: "A lower-than-expected unemployment rate usually supports the currency if it signals labor resilience.",
    weakerOutcome: "A higher-than-expected unemployment rate usually pressures the currency if it signals cooling growth or rising slack.",
    contextNote: "This is more useful as part of the full labor packet than as a standalone trigger.",
    whatToCompare: ["Actual versus forecast", "Actual versus previous", "Participation or employment details when available", "Whether price accepts or rejects the first move"],
    tradingWorkflow: [
      "Before release: know whether the market cares more about recession risk or inflation pressure.",
      "At release: check whether unemployment confirms or contradicts the headline jobs number.",
      "After release: watch whether the currency reaction survives the first retracement.",
    ],
    commonTraps: ["Treating a lower unemployment rate as always bullish without checking participation", "Ignoring wage or employment-change details"],
  },
  {
    family: "labor",
    familyLabel: "Labor / Wages",
    includeAny: ["average hourly earnings", "average weekly earnings", "wages", "earnings"],
    resultDirection: "higher_supports_currency",
    knowledgeDepth: "specific",
    marketSensitivity: "High when inflation persistence is the dominant macro question.",
    whatItIs: "Wage and earnings releases measure pay growth across workers or a defined labor-market segment.",
    whyTradersCare: "Wages can feed services inflation and influence how comfortable a central bank is with cutting or holding rates.",
    mayAffect: ["The event currency", "Rate-sensitive FX pairs", "Bond-yield expectations"],
    priceCaveats: [
      "Hot wages can support the currency through rates, but hurt risk appetite if inflation fear dominates.",
      "Wage data can conflict with employment or unemployment details.",
    ],
    educationalSummary: "Wages matter because they help traders judge whether inflation pressure is cooling or still embedded in the labor market.",
    strongerOutcome: "Higher-than-expected wage growth can support the currency when it keeps policy expectations firmer.",
    weakerOutcome: "Lower-than-expected wage growth can pressure the currency when it reduces inflation or policy-tightening pressure.",
    contextNote: "This matters most when central banks are focused on sticky services inflation or wage-price persistence.",
    whatToCompare: ["Actual versus forecast", "Actual versus previous", "Headline labor details released at the same time", "The central bank's current inflation focus"],
    tradingWorkflow: [
      "Before release: decide whether wages are the market's main concern or just a secondary detail.",
      "At release: check if wages confirm or contradict jobs/unemployment.",
      "After release: prefer follow-through only when rates-sensitive pairs confirm the wage signal.",
    ],
    commonTraps: ["Ignoring wages during sticky-inflation regimes", "Assuming jobs and wages always point in the same direction"],
  },
  {
    family: "labor",
    familyLabel: "Labor / Claims",
    includeAny: ["claimant count", "jobless claims", "unemployment claims"],
    resultDirection: "lower_supports_currency",
    knowledgeDepth: "specific",
    marketSensitivity: "Medium to high when traders are watching for labor-market deterioration.",
    whatItIs: "Claims-style releases track people filing for unemployment-related support or benefits.",
    whyTradersCare: "They can show labor weakness earlier than slower official employment reports.",
    mayAffect: ["The event currency", "Short-term rate expectations", "Risk sentiment when claims surprise sharply"],
    priceCaveats: [
      "Claims can be noisy week to week or month to month.",
      "The market may ignore a small move if larger labor data is nearby.",
    ],
    educationalSummary: "Claims data is a labor-temperature check: rising claims point to weaker employment conditions, while falling claims suggest resilience.",
    strongerOutcome: "Lower-than-expected claims usually support the currency if they show labor strength.",
    weakerOutcome: "Higher-than-expected claims usually pressure the currency if they point to labor cooling.",
    contextNote: "Use it as a warning light or confirmation layer, not as a complete labor thesis by itself.",
    whatToCompare: ["Actual versus forecast", "Trend over recent releases", "Whether a larger labor report is due soon"],
    tradingWorkflow: [
      "Before release: identify whether labor deterioration is already a market theme.",
      "At release: classify the surprise, then check whether the affected currency reacts broadly.",
      "After release: fade caution rises if price ignores a meaningful surprise.",
    ],
    commonTraps: ["Overreacting to one noisy claims print", "Ignoring whether larger labor data is imminent"],
  },
  {
    family: "inflation",
    familyLabel: "Inflation",
    includeAny: ["core cpi", "cpi", "hicp", "cpih"],
    resultDirection: "contextual",
    knowledgeDepth: "specific",
    marketSensitivity: "Very high when central-bank policy is sensitive to inflation progress.",
    whatItIs: "CPI-style releases measure consumer-price changes. Core versions strip volatile components to show underlying inflation pressure.",
    whyTradersCare: "Inflation can change expected policy rates, real yields, and whether current central-bank policy is restrictive enough.",
    mayAffect: ["The event currency", "Major FX pairs", "Gold", "Bond-yield expectations", "Equity-index risk mood"],
    priceCaveats: [
      "A hot print is not automatically bullish if growth fear or risk-off pressure dominates.",
      "Markets often care more about core, services, or monthly momentum than the headline.",
    ],
    educationalSummary: "For traders, CPI is a policy-pressure event. It asks whether inflation gives the central bank room to ease, forces patience, or creates renewed tightening risk.",
    strongerOutcome: "Hotter-than-expected inflation can support the currency if traders price tighter policy or fewer cuts.",
    weakerOutcome: "Softer-than-expected inflation can pressure the currency if traders price easier policy or faster cuts.",
    contextNote: "The same CPI surprise can mean different things depending on the central bank's current reaction function.",
    whatToCompare: ["Actual versus forecast", "Core versus headline", "Monthly momentum", "Previous value", "Central-bank inflation narrative"],
    tradingWorkflow: [
      "Before release: know whether the market is focused on headline inflation, core inflation, or services persistence.",
      "At release: check whether the surprise changes rate-path expectations or only creates a short spike.",
      "After release: confirm with broad currency movement and whether gold/yields-sensitive markets agree.",
    ],
    commonTraps: ["Treating hot CPI as always bullish", "Ignoring core details", "Trading before the second candle confirms acceptance"],
  },
  {
    family: "inflation",
    familyLabel: "Inflation / PCE",
    includeAny: ["core pce", "pce price", "pce"],
    resultDirection: "contextual",
    knowledgeDepth: "specific",
    marketSensitivity: "High for USD because PCE is closely tied to the Fed's preferred inflation framework.",
    whatItIs: "PCE measures consumer-price changes through a spending-based lens. Core PCE removes volatile components to focus on underlying pressure.",
    whyTradersCare: "For the U.S., PCE can validate or challenge what traders inferred from CPI and payroll/wage data.",
    mayAffect: ["USD pairs", "Gold", "Treasury expectations", "U.S. equity indices"],
    priceCaveats: [
      "PCE may move less than CPI if CPI already gave the market the inflation signal.",
      "Core PCE often matters more than headline PCE in Fed-sensitive regimes.",
    ],
    educationalSummary: "PCE is a confirmation or correction event for the inflation path the Fed cares about.",
    strongerOutcome: "Hotter PCE can support USD if it keeps Fed expectations firmer.",
    weakerOutcome: "Softer PCE can pressure USD if it supports easier Fed expectations.",
    contextNote: "Use PCE to ask whether earlier CPI-driven price action deserves follow-through.",
    whatToCompare: ["Actual versus forecast", "Core versus headline", "CPI signal from earlier in the month", "Fed speakers after the release"],
    tradingWorkflow: [
      "Before release: check whether CPI already moved the inflation story.",
      "At release: decide whether PCE confirms or contradicts that story.",
      "After release: watch whether USD pairs extend beyond the first impulse.",
    ],
    commonTraps: ["Expecting CPI-sized movement every time", "Ignoring whether the print is old news after CPI"],
  },
  {
    family: "inflation",
    familyLabel: "Inflation / Producer Prices",
    includeAny: ["ppi", "producer price", "producer prices"],
    resultDirection: "contextual",
    knowledgeDepth: "specific",
    marketSensitivity: "Medium to high when traders are searching for upstream inflation pressure.",
    whatItIs: "PPI measures price changes received by producers before costs fully reach consumers.",
    whyTradersCare: "Producer prices can hint at future consumer inflation pressure and margin stress.",
    mayAffect: ["The event currency", "Inflation-sensitive FX pairs", "Bond-yield expectations"],
    priceCaveats: [
      "PPI is usually less decisive than CPI or policy decisions.",
      "Pass-through from producer prices to consumer inflation is not automatic.",
    ],
    educationalSummary: "PPI is an upstream inflation check. It matters most when it confirms or challenges the broader inflation direction.",
    strongerOutcome: "Higher PPI can support the currency through policy pressure if traders think inflation risk is rising.",
    weakerOutcome: "Lower PPI can pressure the currency if it supports a softer inflation path.",
    contextNote: "Treat PPI as supporting evidence unless it is a large surprise or CPI expectations are highly sensitive.",
    whatToCompare: ["Actual versus forecast", "Core if available", "Recent CPI trend", "Whether central-bank rhetoric mentions pipeline pressure"],
    tradingWorkflow: [
      "Before release: decide whether inflation is currently the main market theme.",
      "At release: classify whether PPI confirms or contradicts CPI direction.",
      "After release: require price follow-through because PPI alone can be ignored.",
    ],
    commonTraps: ["Overweighting PPI versus CPI", "Assuming producer-price pressure always passes through to consumers"],
  },
  {
    family: "policy",
    familyLabel: "Policy / Rates",
    includeAny: ["interest rate decision", "deposit facility rate", "policy rate", "rate statement", "fomc statement", "monetary policy statement"],
    excludeAny: ["auction"],
    resultDirection: "contextual",
    knowledgeDepth: "specific",
    marketSensitivity: "Very high when markets are uncertain about the next central-bank step.",
    whatItIs: "Policy events announce or explain central-bank decisions, rate settings, voting behavior, and guidance.",
    whyTradersCare: "Currencies often reprice when traders adjust expected rate differentials and the future policy path.",
    mayAffect: ["The event currency", "Major FX pairs", "Rates-sensitive assets", "Gold", "Broad risk sentiment for major central banks"],
    priceCaveats: [
      "The decision can be fully priced; the statement, vote split, projections, or press conference may matter more.",
      "A hold can be hawkish or dovish depending on guidance.",
    ],
    educationalSummary: "Policy events are about forward expectations, not only the headline decision.",
    strongerOutcome: "A more hawkish outcome can support the currency if it implies tighter policy or fewer cuts than expected.",
    weakerOutcome: "A more dovish outcome can weaken the currency if it implies easier policy or more cuts than expected.",
    contextNote: "Read the event as decision plus guidance plus market pricing, not as a single number.",
    whatToCompare: ["Decision versus consensus", "Statement tone", "Vote split", "Press conference or projections", "Prior central-bank guidance"],
    tradingWorkflow: [
      "Before release: know what the market expected from the central bank.",
      "At release: separate the headline decision from guidance.",
      "After release: wait for the press-conference/projection phase when relevant before trusting direction.",
    ],
    commonTraps: ["Calling a hold neutral without reading guidance", "Trading the first move before statement details are digested"],
  },
  {
    family: "policy",
    familyLabel: "Central Bank Communication",
    includeAny: ["speech", "speaks", "testimony", "minutes"],
    resultDirection: "contextual",
    knowledgeDepth: "specific",
    marketSensitivity: "Contextual. It rises sharply when a policymaker is expected to clarify the rate path.",
    whatItIs: "Central-bank communication includes speeches, testimony, and meeting minutes that reveal policy priorities and reaction functions.",
    whyTradersCare: "The market listens for whether policymakers sound more hawkish, dovish, worried about inflation, or worried about growth.",
    mayAffect: ["The event currency", "Rate-sensitive FX pairs", "Gold and yields when the speaker is influential"],
    priceCaveats: [
      "Some speeches are ceremonial and do not include policy content.",
      "Minutes can be stale if newer data has already changed the market's view.",
    ],
    educationalSummary: "Communication events matter when they change how traders interpret the next inflation, labor, or growth release.",
    strongerOutcome: "A more hawkish tone can support the currency if it pushes rate expectations higher.",
    weakerOutcome: "A more dovish tone can pressure the currency if it softens rate expectations.",
    contextNote: "This is a tone event. The useful question is whether it changes the reaction function for future data.",
    whatToCompare: ["Speaker importance", "Policy voting role", "Tone versus previous comments", "Whether markets move during the remarks"],
    tradingWorkflow: [
      "Before event: identify whether the speaker is decision-relevant.",
      "During event: watch for policy-path language, inflation concern, or growth concern.",
      "After event: treat no price reaction as evidence the speech did not add a tradable theme.",
    ],
    commonTraps: ["Treating every speech as high-quality event risk", "Ignoring whether remarks are already known or ceremonial"],
  },
  {
    family: "gdp",
    familyLabel: "Growth / GDP",
    includeAny: ["gdp", "gross domestic product"],
    resultDirection: "higher_supports_currency",
    knowledgeDepth: "specific",
    marketSensitivity: "Medium to high when growth divergence or recession risk is the active theme.",
    whatItIs: "GDP measures broad economic output over the reported period.",
    whyTradersCare: "It shows whether an economy is outperforming, stagnating, or weakening relative to expectations.",
    mayAffect: ["The event currency", "Growth-sensitive pairs", "Equity and risk sentiment if the country is systemically important"],
    priceCaveats: [
      "GDP can lag current conditions and may move less than inflation or policy events.",
      "Components and revisions can change the meaning of the headline.",
    ],
    educationalSummary: "GDP is a broad growth scorecard. In FX it matters most when one economy is visibly diverging from another.",
    strongerOutcome: "A stronger GDP print can support the currency if it reinforces relative growth strength.",
    weakerOutcome: "A weaker GDP print can pressure the currency if it raises slowdown or easing expectations.",
    contextNote: "Pair context matters: GDP is most useful when comparing base-economy momentum versus quote-economy momentum.",
    whatToCompare: ["Actual versus forecast", "Annualized versus quarterly measure", "Revisions", "Consumption, investment, and net-export components when available"],
    tradingWorkflow: [
      "Before release: decide whether growth is currently moving the currency or policy/inflation is dominant.",
      "At release: classify headline and components together.",
      "After release: prefer pairs where growth surprise aligns with existing price direction.",
    ],
    commonTraps: ["Overweighting old GDP data", "Ignoring revisions or composition"],
  },
  {
    family: "activity",
    familyLabel: "Activity / PMI / ISM",
    includeAny: ["pmi", "ism"],
    resultDirection: "higher_supports_currency",
    knowledgeDepth: "specific",
    marketSensitivity: "Medium to high because PMIs can reveal turning points earlier than official data.",
    whatItIs: "PMI and ISM surveys track business activity, new orders, employment, supplier delivery, and price pressure.",
    whyTradersCare: "They give an early pulse on whether growth is expanding, slowing, or contracting.",
    mayAffect: ["The event currency", "Equity-index sentiment", "Commodity and cyclical FX themes"],
    priceCaveats: [
      "Subcomponents can matter more than the headline.",
      "Manufacturing can be less important than services when services dominate the economy.",
    ],
    educationalSummary: "PMIs are early warning tools for growth momentum and sometimes inflation pressure.",
    strongerOutcome: "A stronger PMI can support the currency if it signals better growth or sticky price pressure.",
    weakerOutcome: "A weaker PMI can pressure the currency if it signals cooling demand or slowdown risk.",
    contextNote: "The 50 line matters: above 50 usually implies expansion, below 50 contraction.",
    whatToCompare: ["Actual versus forecast", "Above or below 50", "New orders", "Employment", "Prices paid"],
    tradingWorkflow: [
      "Before release: know whether manufacturing, services, or composite is the more important release.",
      "At release: check headline and subcomponents.",
      "After release: trust the signal more when multiple activity releases point the same way.",
    ],
    commonTraps: ["Trading headline PMI while ignoring prices or employment", "Treating a small move around 50 as decisive"],
  },
  {
    family: "activity",
    familyLabel: "Activity / Consumer Demand",
    includeAny: ["retail sales", "electronic card retail sales"],
    resultDirection: "higher_supports_currency",
    knowledgeDepth: "specific",
    marketSensitivity: "Medium to high when consumer resilience is the active growth question.",
    whatItIs: "Retail-sales releases measure spending through retailers or payment-card channels.",
    whyTradersCare: "Consumer demand drives a large part of growth in many economies and can influence policy expectations.",
    mayAffect: ["The event currency", "Growth-sensitive pairs", "Equity sentiment"],
    priceCaveats: [
      "Headline sales can be distorted by inflation, fuel, autos, or seasonal effects.",
      "The market may care more about core/control measures than headline sales.",
    ],
    educationalSummary: "Retail sales tell traders whether households are still spending or demand is rolling over.",
    strongerOutcome: "Stronger sales can support the currency when they reinforce resilient growth.",
    weakerOutcome: "Weaker sales can pressure the currency when they signal demand deterioration.",
    contextNote: "This is most powerful when growth resilience is being debated.",
    whatToCompare: ["Actual versus forecast", "Core/control if available", "Actual versus previous", "Whether inflation is inflating nominal spending"],
    tradingWorkflow: [
      "Before release: identify if consumer demand is currently driving the currency story.",
      "At release: separate broad headline from cleaner core demand where available.",
      "After release: look for confirmation in related growth-sensitive pairs.",
    ],
    commonTraps: ["Ignoring inflation effects", "Overweighting volatile categories"],
  },
  {
    family: "activity",
    familyLabel: "Activity / Industrial Production",
    includeAny: ["industrial production", "capacity utilization"],
    resultDirection: "higher_supports_currency",
    knowledgeDepth: "specific",
    marketSensitivity: "Medium, higher for manufacturing-heavy or export-sensitive economies.",
    whatItIs: "Industrial production tracks output from factories, mines, and utilities. Capacity utilization shows how much productive capacity is being used.",
    whyTradersCare: "It helps show whether real-economy production is improving or losing momentum.",
    mayAffect: ["The event currency", "Cyclical FX themes", "Equity and commodity sentiment"],
    priceCaveats: [
      "It is usually less explosive than CPI, labor, or policy events.",
      "Weather, energy, and one-off production swings can distort the release.",
    ],
    educationalSummary: "Industrial production is a real-activity check, useful for confirming whether growth momentum is broadening or fading.",
    strongerOutcome: "A stronger print can support the currency if it confirms better activity.",
    weakerOutcome: "A weaker print can pressure the currency if it confirms slowdown risk.",
    contextNote: "It works best as confirmation for an existing growth theme.",
    whatToCompare: ["Actual versus forecast", "Actual versus previous", "Trend over several releases", "PMI direction"],
    tradingWorkflow: [
      "Before release: check whether industrial activity matters for that currency right now.",
      "At release: classify the surprise and compare it to PMI signals.",
      "After release: require price confirmation because this event can be ignored.",
    ],
    commonTraps: ["Expecting a large standalone move", "Ignoring whether PMIs already gave the signal"],
  },
  {
    family: "activity",
    familyLabel: "Housing / Construction",
    includeAny: ["building permits", "housing starts", "new home sales", "existing home sales", "pending home sales", "house price"],
    resultDirection: "higher_supports_currency",
    knowledgeDepth: "specific",
    marketSensitivity: "Usually medium, but can rise when housing is central to growth or rate sensitivity.",
    whatItIs: "Housing releases measure construction permission, home sales, or housing-market demand.",
    whyTradersCare: "Housing is rate-sensitive and can reveal whether high interest rates are biting the real economy.",
    mayAffect: ["The event currency", "Rate-sensitive assets", "Domestic-growth themes"],
    priceCaveats: [
      "Housing data is often secondary unless the market is focused on growth stress.",
      "Monthly readings can be volatile.",
    ],
    educationalSummary: "Housing data is a rate-sensitivity check: strong housing suggests resilience, weak housing suggests restrictive policy is hurting demand.",
    strongerOutcome: "A stronger housing print can support the currency when it reinforces growth resilience.",
    weakerOutcome: "A weaker print can pressure the currency when it raises slowdown or easing expectations.",
    contextNote: "Treat housing as a supporting input unless the release is unusually large or the market is already focused on housing stress.",
    whatToCompare: ["Actual versus forecast", "Actual versus previous", "Mortgage-rate environment", "Recent growth data"],
    tradingWorkflow: [
      "Before release: decide whether housing is part of the active macro story.",
      "At release: classify surprise size.",
      "After release: only promote the signal if price confirms beyond the first reaction.",
    ],
    commonTraps: ["Treating housing as equal to CPI or rate decisions", "Ignoring volatile monthly noise"],
  },
  {
    family: "trade_confidence",
    familyLabel: "Trade / External Balance",
    includeAny: ["trade balance", "current account"],
    resultDirection: "higher_supports_currency",
    knowledgeDepth: "specific",
    marketSensitivity: "Medium, higher for export-led or external-balance-sensitive economies.",
    whatItIs: "Trade balance and current-account releases show whether a country is running a surplus or deficit with the rest of the world.",
    whyTradersCare: "External balance can influence currency demand, growth quality, and vulnerability to funding stress.",
    mayAffect: ["The event currency", "Export-sensitive currencies", "Regional growth themes"],
    priceCaveats: [
      "Trade data often matters less than policy, inflation, or labor.",
      "A better balance can come from weak imports rather than strong exports.",
    ],
    educationalSummary: "Trade data tells traders whether external demand and currency-flow pressure are improving or worsening.",
    strongerOutcome: "A higher surplus or smaller deficit can support the currency if it reflects healthier external demand.",
    weakerOutcome: "A lower surplus or wider deficit can pressure the currency if it points to weaker external balance.",
    contextNote: "Check whether the improvement comes from exports rising or imports collapsing.",
    whatToCompare: ["Actual versus forecast", "Surplus/deficit direction", "Exports versus imports if available", "Currency's export sensitivity"],
    tradingWorkflow: [
      "Before release: know whether trade is relevant to the currency's current story.",
      "At release: classify whether external balance improved or worsened.",
      "After release: use it as context unless price reaction is broad and sustained.",
    ],
    commonTraps: ["Assuming a better balance always means stronger growth", "Ignoring whether imports collapsed"],
  },
  {
    family: "trade_confidence",
    familyLabel: "Confidence / Sentiment",
    includeAny: ["consumer confidence", "business confidence", "sentiment", "zew", "sentix"],
    resultDirection: "higher_supports_currency",
    knowledgeDepth: "specific",
    marketSensitivity: "Medium when sentiment is being watched for turning-point evidence.",
    whatItIs: "Confidence and sentiment surveys measure how households, businesses, or investors feel about current and future conditions.",
    whyTradersCare: "Sentiment can foreshadow spending, investment, and growth momentum.",
    mayAffect: ["The event currency", "Growth-sensitive pairs", "Regional equity sentiment"],
    priceCaveats: [
      "Soft survey data can diverge from hard activity data.",
      "The market may ignore it when larger releases are nearby.",
    ],
    educationalSummary: "Confidence data is an early mood indicator, useful when traders are looking for a turn in growth expectations.",
    strongerOutcome: "A stronger sentiment reading can support the currency if it improves growth expectations.",
    weakerOutcome: "A weaker reading can pressure the currency if it reinforces slowdown concerns.",
    contextNote: "Use sentiment as an early warning layer, not a complete macro verdict.",
    whatToCompare: ["Actual versus forecast", "Trend over several releases", "Hard data confirmation", "Nearby larger events"],
    tradingWorkflow: [
      "Before release: decide whether sentiment is currently market-moving for this currency.",
      "At release: classify the direction and size of the surprise.",
      "After release: wait for price to prove the market cares.",
    ],
    commonTraps: ["Overweighting surveys when hard data disagrees", "Trading small confidence misses as major catalysts"],
  },
  {
    family: "generic",
    familyLabel: "Productivity",
    includeAny: ["labour productivity", "labor productivity", "productivity"],
    resultDirection: "higher_supports_currency",
    knowledgeDepth: "specific",
    marketSensitivity: "Usually low to medium unless productivity is central to inflation, wages, or growth debates.",
    whatItIs: "Productivity measures output per worker or per hour worked over a period.",
    whyTradersCare: "Higher productivity can support growth without the same inflation pressure, while weak productivity can make wage growth more inflationary.",
    mayAffect: ["The event currency", "Longer-term growth and inflation narratives"],
    priceCaveats: [
      "Productivity rarely moves FX by itself unless the surprise is large.",
      "It is usually slower-moving context rather than an immediate trade catalyst.",
    ],
    educationalSummary: "Productivity tells traders whether the economy is producing more efficiently, which can affect long-run growth and inflation pressure.",
    strongerOutcome: "Higher productivity can support the currency if it improves the growth-quality story.",
    weakerOutcome: "Lower productivity can pressure the currency if it suggests weaker efficiency or more inflationary wage pressure.",
    contextNote: "In live trading, this is usually context, not a primary trigger.",
    whatToCompare: ["Actual versus forecast", "Actual versus previous", "Whether wage growth is also in focus"],
    tradingWorkflow: [
      "Before release: treat it as secondary unless productivity is already a theme.",
      "At release: classify the surprise but avoid overreacting.",
      "After release: promote it only if price and broader macro context care.",
    ],
    commonTraps: ["Treating productivity as a high-speed catalyst", "Ignoring the wage/inflation context"],
  },
  {
    family: "generic",
    familyLabel: "Capital Flows",
    includeAny: ["tic ", "capital flow", "foreign purchases"],
    resultDirection: "higher_supports_currency",
    knowledgeDepth: "specific",
    marketSensitivity: "Usually medium for USD, higher when foreign demand for U.S. assets is the active story.",
    whatItIs: "TIC and capital-flow releases track cross-border purchases, sales, and flows into domestic financial assets.",
    whyTradersCare: "They can show whether foreign capital demand is supporting or withdrawing from a currency's asset markets.",
    mayAffect: ["The event currency", "Bond-market narratives", "Longer-term currency-flow themes"],
    priceCaveats: [
      "Capital-flow data is delayed and often not a fast intraday catalyst.",
      "Flow composition matters more than one headline number.",
    ],
    educationalSummary: "Capital-flow data is about funding and asset demand, not immediate growth or inflation.",
    strongerOutcome: "Stronger inflows can support the currency if they show healthier foreign demand for domestic assets.",
    weakerOutcome: "Weaker inflows or outflows can pressure the currency if they show fading demand.",
    contextNote: "Use this as a background flow clue rather than a primary release trigger.",
    whatToCompare: ["Actual versus forecast", "Long-term versus short-term flows", "Trend over several releases"],
    tradingWorkflow: [
      "Before release: treat as context unless flow themes are prominent.",
      "At release: check whether the number changes the asset-demand story.",
      "After release: require strong price confirmation before acting on it.",
    ],
    commonTraps: ["Trading delayed flow data as if it were CPI", "Ignoring composition of flows"],
  },
];

export function findCalendarEventDefinition(title: string): CalendarEventDefinition | null {
  const normalized = normalizeText(title);
  if (!normalized) return null;

  return (
    CALENDAR_EVENT_DEFINITIONS.find((definition) => {
      if (definition.exactTitles?.some((exact) => normalizeText(exact) === normalized)) {
        return true;
      }
      if (includesAny(normalized, definition.excludeAny)) {
        return false;
      }
      return includesAny(normalized, definition.includeAny) || includesAllGroup(normalized, definition.includeAll);
    }) ?? null
  );
}
