import { normalizePairMatrixSeriesTitle } from "@/app/lib/pairMatrixSnapshot";
import type { CalendarEvent } from "@/app/types";

export type PairMatrixMomentumPillar = "economy" | "inflation" | "policy";
export type PairMatrixEconomyFactorId = "activity" | "labor" | "retail" | "sentiment" | "trade";
export type PairMatrixMomentumDirection = "higher_is_better" | "lower_is_better" | "higher_is_hotter" | "policy_action";

export const PAIR_MATRIX_MOMENTUM_SOURCE_REFERENCES = {
  fed_policy: "https://www.federalreserve.gov/economy-at-a-glance-policy-rate.htm",
  ecb_policy: "https://www.ecb.europa.eu/stats/policy_and_exchange_rates/key_ecb_interest_rates/html/index.en.html",
  boe_policy: "https://www.bankofengland.co.uk/monetary-policy",
  boj_policy: "https://www.boj.or.jp/en/mopo/outline/",
  rba_policy: "https://www.rba.gov.au/cash-rate-target-overview.html",
  boc_policy: "https://www.bankofcanada.ca/core-functions/monetary-policy/key-interest-rate/",
  rbnz_policy: "https://www.rbnz.govt.nz/en/monetary-policy/about-monetary-policy/the-official-cash-rate",
  snb_policy: "https://www.snb.ch/en/the-snb/mandates-goals/monetary-policy",
  consumer_prices: "https://www.bls.gov/cpi/questions-and-answers.htm",
  producer_prices: "https://www.bls.gov/ppi/",
  labor: "https://www.bls.gov/cps/definitions.htm",
  gdp: "https://www.bea.gov/data/gdp/gross-domestic-product",
  pmi: "https://www.spglobal.com/marketintelligence/en/mi/products/pmi.html",
  retail: "https://www.census.gov/retail/index.html",
  sentiment: "https://www.oecd.org/en/data/indicators/consumer-confidence-index-cci.html",
  external_balance: "https://www.oecd.org/en/data/indicators/current-account-balance.html",
} as const;

export type PairMatrixMomentumSourceKey = keyof typeof PAIR_MATRIX_MOMENTUM_SOURCE_REFERENCES;

export interface PairMatrixMomentumRegistryEntry {
  id: string;
  label: string;
  pillar: PairMatrixMomentumPillar;
  factor?: PairMatrixEconomyFactorId;
  scoreGroup: string;
  direction: PairMatrixMomentumDirection;
  includeAny: readonly string[];
  excludeAny?: readonly string[];
  currencies?: readonly string[];
  canonicalPolicy?: boolean;
  policyPriority?: number;
  rationale: string;
  sourceKey: PairMatrixMomentumSourceKey;
}

// Pair Matrix owns this registry. Keep it conservative and auditable: a broker
// title that does not match one of these entries remains visible but unscored.
export const PAIR_MATRIX_MOMENTUM_REGISTRY: readonly PairMatrixMomentumRegistryEntry[] = [
  {
    id: "usd_primary_policy_rate",
    label: "Fed policy rate",
    pillar: "policy",
    scoreGroup: "primary_policy_rate",
    direction: "policy_action",
    currencies: ["USD"],
    canonicalPolicy: true,
    policyPriority: 100,
    includeAny: ["fed interest rate decision", "federal funds rate decision", "fomc interest rate decision"],
    excludeAny: ["statement", "minutes", "conference", "speech", "testimony"],
    rationale: "The configured primary numerical Federal Reserve decision; guidance remains outside this arithmetic state.",
    sourceKey: "fed_policy",
  },
  {
    id: "eur_primary_policy_rate",
    label: "ECB deposit facility rate",
    pillar: "policy",
    scoreGroup: "primary_policy_rate",
    direction: "policy_action",
    currencies: ["EUR"],
    canonicalPolicy: true,
    policyPriority: 100,
    includeAny: ["ecb deposit facility rate decision", "deposit facility rate decision"],
    excludeAny: ["statement", "minutes", "conference", "speech"],
    rationale: "The ECB deposit facility rate is the configured primary numerical policy decision for the euro.",
    sourceKey: "ecb_policy",
  },
  {
    id: "gbp_primary_policy_rate",
    label: "BoE bank rate",
    pillar: "policy",
    scoreGroup: "primary_policy_rate",
    direction: "policy_action",
    currencies: ["GBP"],
    canonicalPolicy: true,
    policyPriority: 100,
    includeAny: ["boe interest rate decision", "bank rate decision", "official bank rate"],
    excludeAny: ["statement", "minutes", "conference", "speech"],
    rationale: "The Bank of England Bank Rate is the configured primary policy decision for sterling.",
    sourceKey: "boe_policy",
  },
  {
    id: "jpy_primary_policy_rate",
    label: "BoJ policy rate",
    pillar: "policy",
    scoreGroup: "primary_policy_rate",
    direction: "policy_action",
    currencies: ["JPY"],
    canonicalPolicy: true,
    policyPriority: 100,
    includeAny: ["boj interest rate decision", "boj policy rate", "bank of japan interest rate decision"],
    excludeAny: ["statement", "minutes", "conference", "speech"],
    rationale: "The numerical Bank of Japan policy-rate decision is used; qualitative guidance is not inferred.",
    sourceKey: "boj_policy",
  },
  {
    id: "aud_primary_policy_rate",
    label: "RBA cash rate",
    pillar: "policy",
    scoreGroup: "primary_policy_rate",
    direction: "policy_action",
    currencies: ["AUD"],
    canonicalPolicy: true,
    policyPriority: 100,
    includeAny: ["rba interest rate decision", "rba cash rate", "cash rate target"],
    excludeAny: ["statement", "minutes", "conference", "speech"],
    rationale: "The RBA cash-rate target is the configured primary policy decision for AUD.",
    sourceKey: "rba_policy",
  },
  {
    id: "cad_primary_policy_rate",
    label: "BoC overnight rate",
    pillar: "policy",
    scoreGroup: "primary_policy_rate",
    direction: "policy_action",
    currencies: ["CAD"],
    canonicalPolicy: true,
    policyPriority: 100,
    includeAny: ["boc interest rate decision", "overnight rate decision", "bank of canada interest rate decision"],
    excludeAny: ["statement", "minutes", "conference", "speech"],
    rationale: "The Bank of Canada overnight-rate decision is the configured primary policy decision for CAD.",
    sourceKey: "boc_policy",
  },
  {
    id: "nzd_primary_policy_rate",
    label: "RBNZ official cash rate",
    pillar: "policy",
    scoreGroup: "primary_policy_rate",
    direction: "policy_action",
    currencies: ["NZD"],
    canonicalPolicy: true,
    policyPriority: 100,
    includeAny: ["rbnz interest rate decision", "official cash rate", "rbnz cash rate"],
    excludeAny: ["statement", "minutes", "conference", "speech"],
    rationale: "The RBNZ Official Cash Rate is the configured primary policy decision for NZD.",
    sourceKey: "rbnz_policy",
  },
  {
    id: "chf_primary_policy_rate",
    label: "SNB policy rate",
    pillar: "policy",
    scoreGroup: "primary_policy_rate",
    direction: "policy_action",
    currencies: ["CHF"],
    canonicalPolicy: true,
    policyPriority: 100,
    includeAny: ["snb interest rate decision", "snb policy rate", "swiss national bank interest rate decision"],
    excludeAny: ["statement", "minutes", "conference", "speech"],
    rationale: "The SNB policy rate is the configured primary numerical decision for CHF.",
    sourceKey: "snb_policy",
  },
  {
    id: "core_consumer_inflation",
    label: "Core consumer inflation",
    pillar: "inflation",
    scoreGroup: "core_consumer_inflation",
    direction: "higher_is_hotter",
    includeAny: ["core cpi", "core hicp", "core pce", "trimmed mean cpi", "weighted median cpi", "median cpi"],
    excludeAny: ["expectation"],
    rationale: "Higher core consumer-price readings indicate hotter underlying inflation within the same exact series.",
    sourceKey: "consumer_prices",
  },
  {
    id: "producer_inflation",
    label: "Producer inflation",
    pillar: "inflation",
    scoreGroup: "producer_inflation",
    direction: "higher_is_hotter",
    includeAny: ["ppi", "producer price"],
    excludeAny: ["expectation"],
    rationale: "Higher producer-price readings indicate hotter upstream inflation; the group remains separate from consumer inflation.",
    sourceKey: "producer_prices",
  },
  {
    id: "headline_consumer_inflation",
    label: "Headline consumer inflation",
    pillar: "inflation",
    scoreGroup: "headline_consumer_inflation",
    direction: "higher_is_hotter",
    includeAny: ["cpi", "hicp", "cpih", "consumer price", "pce price", "inflation rate"],
    excludeAny: ["core", "trimmed", "median", "producer", "ppi", "expectation"],
    rationale: "Higher headline consumer-price readings indicate hotter inflation within the same exact series.",
    sourceKey: "consumer_prices",
  },
  {
    id: "unemployment",
    label: "Unemployment",
    pillar: "economy",
    factor: "labor",
    scoreGroup: "unemployment",
    direction: "lower_is_better",
    includeAny: ["unemployment rate"],
    rationale: "Lower unemployment is treated as improving labor momentum; participation caveats remain visible in the raw data context.",
    sourceKey: "labor",
  },
  {
    id: "labor_claims",
    label: "Labor claims",
    pillar: "economy",
    factor: "labor",
    scoreGroup: "labor_claims",
    direction: "lower_is_better",
    includeAny: ["jobless claims", "unemployment claims", "initial claims", "continuing claims", "claimant count", "jobseekers total"],
    rationale: "Lower claims-style readings are treated as improving labor conditions.",
    sourceKey: "labor",
  },
  {
    id: "labor_wages",
    label: "Wages",
    pillar: "economy",
    factor: "labor",
    scoreGroup: "labor_wages",
    direction: "higher_is_better",
    includeAny: ["average hourly earnings", "average weekly earnings", "wage", "earnings", "labor cash earnings", "labour cash earnings"],
    excludeAny: ["real earnings"],
    rationale: "Higher wages are treated as firmer labor momentum, while their separate inflation implications are not inferred here.",
    sourceKey: "labor",
  },
  {
    id: "employment",
    label: "Employment",
    pillar: "economy",
    factor: "labor",
    scoreGroup: "employment",
    direction: "higher_is_better",
    includeAny: ["nonfarm payroll", "payroll employment", "employment change", "employment rate", "adp employment"],
    excludeAny: ["unemployment"],
    rationale: "Higher employment or payroll readings are treated as improving labor momentum.",
    sourceKey: "labor",
  },
  {
    id: "gdp",
    label: "GDP",
    pillar: "economy",
    factor: "activity",
    scoreGroup: "gdp",
    direction: "higher_is_better",
    includeAny: ["gdp", "gross domestic product"],
    excludeAny: ["price index", "price deflator", "deflator"],
    rationale: "Higher GDP growth or output is treated as improving activity momentum within the same exact series.",
    sourceKey: "gdp",
  },
  {
    id: "composite_activity_survey",
    label: "Composite activity survey",
    pillar: "economy",
    factor: "activity",
    scoreGroup: "pmi_composite",
    direction: "higher_is_better",
    includeAny: ["composite pmi", "composite purchasing managers index"],
    rationale: "Higher composite PMI readings indicate firmer surveyed activity.",
    sourceKey: "pmi",
  },
  {
    id: "services_activity_survey",
    label: "Services activity survey",
    pillar: "economy",
    factor: "activity",
    scoreGroup: "pmi_services",
    direction: "higher_is_better",
    includeAny: ["services pmi", "service pmi", "ism services", "ism non manufacturing", "non manufacturing pmi"],
    rationale: "Higher services PMI/ISM readings indicate firmer surveyed services activity.",
    sourceKey: "pmi",
  },
  {
    id: "manufacturing_activity_survey",
    label: "Manufacturing activity survey",
    pillar: "economy",
    factor: "activity",
    scoreGroup: "pmi_manufacturing",
    direction: "higher_is_better",
    includeAny: ["manufacturing pmi", "ism manufacturing", "manufacturing purchasing managers index"],
    rationale: "Higher manufacturing PMI/ISM readings indicate firmer surveyed manufacturing activity.",
    sourceKey: "pmi",
  },
  {
    id: "generic_activity_survey",
    label: "Activity survey",
    pillar: "economy",
    factor: "activity",
    scoreGroup: "pmi_other",
    direction: "higher_is_better",
    includeAny: ["pmi", "purchasing managers index"],
    rationale: "A conservative fallback for recognized PMI titles not captured by the narrower activity groups.",
    sourceKey: "pmi",
  },
  {
    id: "core_retail_demand",
    label: "Core retail demand",
    pillar: "economy",
    factor: "retail",
    scoreGroup: "retail_core",
    direction: "higher_is_better",
    includeAny: ["retail control", "retail sales excl", "retail sales ex"],
    rationale: "Higher core/control retail readings are treated as improving consumer-demand momentum.",
    sourceKey: "retail",
  },
  {
    id: "headline_retail_demand",
    label: "Retail demand",
    pillar: "economy",
    factor: "retail",
    scoreGroup: "retail_headline",
    direction: "higher_is_better",
    includeAny: ["retail sales", "electronic card retail", "consumer spending", "card spending"],
    excludeAny: ["excl", "excluding", "control"],
    rationale: "Higher headline retail/spending readings are treated as improving consumer-demand momentum.",
    sourceKey: "retail",
  },
  {
    id: "consumer_sentiment",
    label: "Consumer sentiment",
    pillar: "economy",
    factor: "sentiment",
    scoreGroup: "consumer_sentiment",
    direction: "higher_is_better",
    includeAny: ["consumer confidence", "consumer sentiment"],
    excludeAny: ["inflation expectation"],
    rationale: "Higher consumer confidence or sentiment is treated as improving reported sentiment.",
    sourceKey: "sentiment",
  },
  {
    id: "business_sentiment",
    label: "Business sentiment",
    pillar: "economy",
    factor: "sentiment",
    scoreGroup: "business_sentiment",
    direction: "higher_is_better",
    includeAny: ["business confidence", "business climate", "economic sentiment", "zew economic sentiment", "ifo business climate", "sentix"],
    excludeAny: ["inflation expectation"],
    rationale: "Higher business/economic sentiment readings are treated as improving reported sentiment.",
    sourceKey: "sentiment",
  },
  {
    id: "trade_balance",
    label: "Trade balance",
    pillar: "economy",
    factor: "trade",
    scoreGroup: "trade_balance",
    direction: "higher_is_better",
    includeAny: ["trade balance", "goods trade balance", "merchandise trade", "terms of trade"],
    rationale: "A higher balance—including a less-negative deficit—is treated as improving the external-balance reading.",
    sourceKey: "external_balance",
  },
  {
    id: "current_account",
    label: "Current account",
    pillar: "economy",
    factor: "trade",
    scoreGroup: "current_account",
    direction: "higher_is_better",
    includeAny: ["current account"],
    rationale: "A higher current-account balance—including a smaller deficit—is treated as improving the external-balance reading.",
    sourceKey: "external_balance",
  },
] as const;

export function findPairMatrixMomentumRule(event: CalendarEvent): PairMatrixMomentumRegistryEntry | null {
  const title = normalizePairMatrixSeriesTitle(event.title);
  return PAIR_MATRIX_MOMENTUM_REGISTRY.find((entry) => {
    if (entry.currencies && !entry.currencies.includes(event.currency)) return false;
    if (entry.excludeAny?.some((term) => title.includes(normalizePairMatrixSeriesTitle(term)))) return false;
    return entry.includeAny.some((term) => title.includes(normalizePairMatrixSeriesTitle(term)));
  }) ?? null;
}
